INSERT INTO department VALUES (1, 'Cardiology', 69599759);
INSERT INTO department VALUES (2, 'Central Sterile Services Department (CSSD)', 96599439);
INSERT INTO department VALUES (3, 'Chaplaincy', 6628773);
INSERT INTO department VALUES (4, 'Coronary Care Unit (CCU)', 95743549);
INSERT INTO department VALUES (5, 'Critical Care', 96568244);
INSERT INTO department VALUES (6, 'Diagnostic Imaging', 36718497);
INSERT INTO department VALUES (7, 'Discharge Lounge', 98626316);
INSERT INTO department VALUES (8, 'Elderly services', 12394776);
INSERT INTO department VALUES (9, 'Finance Department', 13946434);
INSERT INTO department VALUES (10, 'Gastroenterology', 67442269);
INSERT INTO department VALUES (11, 'General Services', 65806372);
INSERT INTO department VALUES (12, 'General Surgery', 28533315);


INSERT INTO ambulance VALUES (1, true);
INSERT INTO ambulance VALUES (2, true);
INSERT INTO ambulance VALUES (3, true);
INSERT INTO ambulance VALUES (4, true);
INSERT INTO ambulance VALUES (5, true);
INSERT INTO ambulance VALUES (6, false);
INSERT INTO ambulance VALUES (7, true);
INSERT INTO ambulance VALUES (8, true);
INSERT INTO ambulance VALUES (9, false);
INSERT INTO ambulance VALUES (10, false);
INSERT INTO ambulance VALUES (11, false);
INSERT INTO ambulance VALUES (12, false);
INSERT INTO ambulance VALUES (13, true);
INSERT INTO ambulance VALUES (14, true);
INSERT INTO ambulance VALUES (15, true);
INSERT INTO ambulance VALUES (16, true);
INSERT INTO ambulance VALUES (17, false);
INSERT INTO ambulance VALUES (18, false);
INSERT INTO ambulance VALUES (19, false);
INSERT INTO ambulance VALUES (20, false);
INSERT INTO ambulance VALUES (21, true);
INSERT INTO ambulance VALUES (22, false);
INSERT INTO ambulance VALUES (23, false);
INSERT INTO ambulance VALUES (24, false);
INSERT INTO ambulance VALUES (25, false);
INSERT INTO ambulance VALUES (26, true);


INSERT INTO account VALUES (1, 'LOLKA', 'qDKGjmVYW86MIvz');
INSERT INTO account VALUES (2, 'Sleepwalker', '36QNpUm7Yo3lYzfd0apID2');
INSERT INTO account VALUES (3, 'Mother Hen', 'ZaOeoJXaJNQILnYGJuZk');
INSERT INTO account VALUES (4, 'Hairpin', 'zNVKEHddBB7h3XSD9Mtttu');
INSERT INTO account VALUES (5, 'Clover Dragon', 'BWBkJPV0IsmaWITXxVvA0YSm');
INSERT INTO account VALUES (6, 'Teeder', 'PzYvMOh8Y3jdzpkoHqZK8xB');
INSERT INTO account VALUES (7, 'Queen Bee', 'xfBXCc4aU');
INSERT INTO account VALUES (8, 'Ladysmith', 'M810MN5WTkJXbQBsUoS');
INSERT INTO account VALUES (9, 'Drift', 'UMjVX0AbezjxlY');
INSERT INTO account VALUES (10, '42nd Street', 'cSJ46pNIEz');
INSERT INTO account VALUES (11, 'Snapdragon', 'vsGazuralRBLUYGT');
INSERT INTO account VALUES (12, 'Mother Night', '4hfZYXx2YsJJG');
INSERT INTO account VALUES (13, 'Heartbreaker', 'AHObJu88pVpo');
INSERT INTO account VALUES (14, 'Coffee', 'ErjcP4fnkSLJPpx');
INSERT INTO account VALUES (15, 'The Beekeeper', 'TomFG0YEIAz9dvfFIZgBv');
INSERT INTO account VALUES (16, 'Racy Lady', 'EIN8aQNxtcNkFOxzKmMlHvN');
INSERT INTO account VALUES (17, 'Lightweight', 'CSLXRb5uxEJ3M2jdJ3RP');
INSERT INTO account VALUES (18, 'Duchess', 'Mq6Q0mCvBOjBG0C6D0ZI6KN');


INSERT INTO "user" VALUES (1, 'PATRICIA', 'SMITH', 'F', 'nurse', null, null, 'null', '+73716115010', 88, 18);
INSERT INTO "user" VALUES (2, 'LINDA', 'JOHNSON', 'F', 'nurse', null, null, 'null', '+71865291189', 55, 3);
INSERT INTO "user" VALUES (3, 'BARBARA', 'WILLIAMS', 'F', 'patient', null, null, 'null', '+78560615818', 39, 10);
INSERT INTO "user" VALUES (4, 'JAMES', 'JONES', 'M', 'patient', null, null, 'null', '+72781360557', 52, 15);
INSERT INTO "user" VALUES (5, 'ELIZABETH', 'BROWN', 'F', 'patient', null, null, 'null', '+76630037778', 62, 13);
INSERT INTO "user" VALUES (6, 'JENNIFER', 'DAVIS', 'F', 'nurse', null, null, 'null', '+74227283026', 41, 14);
INSERT INTO "user" VALUES (7, 'MARIA', 'MILLER', 'F', 'nurse', null, null, 'null', '+71302810471', 60, 6);
INSERT INTO "user" VALUES (8, 'JOHN', 'WILSON', 'M', 'doctor', null, null, 'null', '+79985395644', 62, 11);
INSERT INTO "user" VALUES (9, 'SUSAN', 'MOORE', 'F', 'patient', null, null, 'null', '+74758405986', 38, 7);
INSERT INTO "user" VALUES (10, 'ROBERT', 'TAYLOR', 'M', 'patient', null, null, 'null', '+79891162357', 34, 4);
INSERT INTO "user" VALUES (11, 'MICHAEL', 'ANDERSON', 'M', 'patient', null, null, 'null', '+78511743884', 35, 12);
INSERT INTO "user" VALUES (12, 'WILLIAM', 'THOMAS', 'M', 'doctor', null, null, 'null', '+79920812686', 67, 1);
INSERT INTO "user" VALUES (13, 'DAVID', 'JACKSON', 'M', 'nurse', null, null, 'null', '+74967614100', 50, 8);
INSERT INTO "user" VALUES (14, 'MARGARET', 'WHITE', 'F', 'nurse', null, null, 'null', '+71447137030', 54, 2);
INSERT INTO "user" VALUES (15, 'RICHARD', 'HARRIS', 'M', 'patient', null, null, 'null', '+78026716713', 88, 17);
INSERT INTO "user" VALUES (16, 'DOROTHY', 'MARTIN', 'F', 'nurse', null, null, 'null', '+72717581603', 58, 9);
INSERT INTO "user" VALUES (17, 'LISA', 'THOMPSON', 'F', 'doctor', null, null, 'null', '+77415047799', 95, 16);
INSERT INTO "user" VALUES (18, 'NANCY', 'GARCIA', 'F', 'nurse', null, null, 'null', '+75166999436', 87, 5);


INSERT INTO notification VALUES (1, 18, 'I need more collegues');
INSERT INTO notification VALUES (2, 9, 'I need more collegues');
INSERT INTO notification VALUES (3, 1, 'I need more collegues');
INSERT INTO notification VALUES (4, 16, 'I need more collegues');
INSERT INTO notification VALUES (5, 2, 'I need more collegues');
INSERT INTO notification VALUES (6, 3, 'I need more collegues');
INSERT INTO notification VALUES (7, 10, 'I need more collegues');
INSERT INTO notification VALUES (8, 17, 'I need more collegues');
INSERT INTO notification VALUES (9, 6, 'I need more collegues');
INSERT INTO notification VALUES (10, 8, 'I need more collegues');


INSERT INTO report VALUES (1, 14, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (2, 5, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (3, 4, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (4, 8, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (5, 15, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (6, 18, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (7, 7, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (8, 17, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (9, 16, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (10, 9, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (11, 6, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (12, 12, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (13, 2, '5000 for advertising to find new doctors');
INSERT INTO report VALUES (14, 10, '5000 for advertising to find new doctors');


INSERT INTO patient VALUES (1, 5, 'Only 10% of your cells are human. The other 90% is made up of 90 trillion microbes that live on you or in you.', DATE '1996-01-29');
INSERT INTO patient VALUES (2, 17, 'Did you know that your stomach acid can dissolve razor blades?', DATE '2009-09-15');
INSERT INTO patient VALUES (3, 4, 'Speaking of the stomach, did you know that you get a new stomach lining every three to four days?', DATE '2012-07-23');
INSERT INTO patient VALUES (4, 1, 'We share 98.4% of our DNA with a chimp – and 70% with a slug.', DATE '2013-11-10');
INSERT INTO patient VALUES (5, 13, 'An adult has fewer bones than a baby!', DATE '2007-08-12');
INSERT INTO patient VALUES (6, 18, 'Mercury is toxic to humans but was used for wounds and medical treatments up until the 20th century.', DATE '2000-08-05');
INSERT INTO patient VALUES (7, 11, 'In the 20th century, lobotomies were legitimate treatments for various mental health illnesses.', DATE '2019-05-26');
INSERT INTO patient VALUES (8, 7, 'Surgeons once believed that bloodletting was beneficial to health. Fevers, apoplexy and headache were thought to be a result of too much blood!', DATE '2007-09-10');
INSERT INTO patient VALUES (9, 9, 'Doctors used to inject paraffin to smooth out wrinkles.', DATE '2018-10-20');
INSERT INTO patient VALUES (10, 3, 'Chloroform was used as the original anaesthetic. Up until the 1950’s when its toxic effects were discovered.', DATE '2008-02-08');
INSERT INTO patient VALUES (11, 15, 'Your eyes blink around 20 times a minute. That’s over ten million times a year!', DATE '2001-01-27');
INSERT INTO patient VALUES (12, 12, 'Your ears never stop growing!', DATE '1992-02-20');
INSERT INTO patient VALUES (13, 6, 'Earwax is actually a type of sweat!', DATE '2004-11-23');
INSERT INTO patient VALUES (14, 10, 'The tongue is covered in about 8,000 taste-buds, each containing up to 100 cells helping you taste your food!', DATE '2005-11-10');
INSERT INTO patient VALUES (15, 16, 'You produce about 40,000 litres of spit in your lifetime. Or to put it another way, enough spit to fill around five hundred bathtubs – yuck!', DATE '2016-11-06');
INSERT INTO patient VALUES (16, 2, 'The average nose produces about a cupful of nasal mucus every day!', DATE '2005-04-07');
INSERT INTO patient VALUES (17, 14, 'You are about 1cm taller in the morning when you first get up than when you go to bed. This is because during the day the soft cartilage between your bones gets squashed and compressed.', DATE '2006-09-02');


INSERT INTO medical_report VALUES (1, 1, 4, 'If you walked for 12 hours a day, it would take the average person 690 days to walk around the world.');
INSERT INTO medical_report VALUES (2, 15, 3, 'The only muscle that never tires is the heart.');
INSERT INTO medical_report VALUES (3, 12, 2, 'The entire surface of your skin is replaced every month, which put another way means you have about 1,000 different skins in your life!');
INSERT INTO medical_report VALUES (4, 16, 17, 'The body has 2.5 million sweat pores.');
INSERT INTO medical_report VALUES (5, 17, 14, 'Every minute you shed over 30,000 dead skin cells.');
INSERT INTO medical_report VALUES (6, 7, 16, 'If you live to age 70, your heart will have beat around 2.5 billion times!');
INSERT INTO medical_report VALUES (7, 2, 6, 'Spread across their lifetime, most people spend an average of one whole year sitting on the toilet.');
INSERT INTO medical_report VALUES (8, 6, 1, 'On average you fart enough in one day to fill a party balloon.');


INSERT INTO appointment VALUES (1, 12, 16, DATE '2019-10-12 04:04:20.041');
INSERT INTO appointment VALUES (2, 15, 6, DATE '2000-03-22 11:15:05.184');
INSERT INTO appointment VALUES (3, 11, 7, DATE '2008-01-21 07:14:22.562');
INSERT INTO appointment VALUES (4, 17, 1, DATE '1993-02-23 05:20:40.099');
INSERT INTO appointment VALUES (5, 16, 13, DATE '2009-05-04 00:48:54.309');
INSERT INTO appointment VALUES (6, 6, 3, DATE '2012-08-30 02:53:55.998');
INSERT INTO appointment VALUES (7, 8, 9, DATE '2006-04-05 15:16:22.933');


INSERT INTO medical_certificate VALUES (1, 6, 13, '2295 days free from job');
INSERT INTO medical_certificate VALUES (2, 10, 4, '769 days free from job');
INSERT INTO medical_certificate VALUES (3, 11, 5, '5774 days free from job');


INSERT INTO invoice VALUES (1, 9, 7, '29257', 'visit to nurse + Alprazolam');
INSERT INTO invoice VALUES (2, 17, 5, '43570', 'visit to nurse + Celebrex');
INSERT INTO invoice VALUES (3, 11, 14, '29265', 'visit to doctor + Bactrim');
INSERT INTO invoice VALUES (4, 16, 2, '21059', 'visit to patient + Fosamax');
INSERT INTO invoice VALUES (5, 18, 10, '28985', 'visit to doctor + Risperidone');
INSERT INTO invoice VALUES (6, 8, 12, '36885', 'visit to patient + Forteo');
INSERT INTO invoice VALUES (7, 1, 6, '32116', 'visit to nurse + Repatha');
INSERT INTO invoice VALUES (8, 7, 15, '4335', 'visit to doctor + Benicar');
INSERT INTO invoice VALUES (9, 5, 4, '5435', 'visit to nurse + Rizatriptan');


INSERT INTO request VALUES (1, 'I need Dulcolax', false);
INSERT INTO request VALUES (2, 'I need Flomax', false);
INSERT INTO request VALUES (3, 'I need Avapro', true);
INSERT INTO request VALUES (4, 'I need Quinapril Hydrochloride', false);
INSERT INTO request VALUES (5, 'I need Enoxaparin', false);
INSERT INTO request VALUES (6, 'I need Demerol', false);
INSERT INTO request VALUES (7, 'I need Desloratadine', false);
INSERT INTO request VALUES (8, 'I need Junel Fe 1.5/30', false);
INSERT INTO request VALUES (9, 'I need Jeuveau', true);
INSERT INTO request VALUES (10, 'I need Etodolac', false);
INSERT INTO request VALUES (11, 'I need Cardizem', true);
INSERT INTO request VALUES (12, 'I need Rivastigmine', true);
INSERT INTO request VALUES (13, 'I need Famotidine', false);
INSERT INTO request VALUES (14, 'I need Guaifenesin', false);
INSERT INTO request VALUES (15, 'I need Qvar', true);
INSERT INTO request VALUES (16, 'I need Belbuca', true);
INSERT INTO request VALUES (17, 'I need Rapaflo', false);
INSERT INTO request VALUES (18, 'I need Celexa', false);
INSERT INTO request VALUES (19, 'I need Bumex', false);
INSERT INTO request VALUES (20, 'I need Furosemide', false);
INSERT INTO request VALUES (21, 'I need Cyanocobalamin', false);
INSERT INTO request VALUES (22, 'I need Zidovudine', true);
INSERT INTO request VALUES (23, 'I need Gemcitabine', true);
INSERT INTO request VALUES (24, 'I need Fexofenadine', true);
INSERT INTO request VALUES (25, 'I need Reglan', false);
INSERT INTO request VALUES (26, 'I need Dexamethasone', true);
INSERT INTO request VALUES (27, 'I need Glucosamine & Chondroitin with MSM', true);
INSERT INTO request VALUES (28, 'I need Zubsolv', true);
INSERT INTO request VALUES (29, 'I need Ergocalciferol', true);
INSERT INTO request VALUES (30, 'I need Reclast', true);
INSERT INTO request VALUES (31, 'I need Zocor', false);
INSERT INTO request VALUES (32, 'I need Brilinta', true);
INSERT INTO request VALUES (33, 'I need Debrox', true);
INSERT INTO request VALUES (34, 'I need Rabeprazole', false);
INSERT INTO request VALUES (35, 'I need Gabapentin Enacarbil', false);
INSERT INTO request VALUES (36, 'I need Fluocinonide', false);
INSERT INTO request VALUES (37, 'I need Fluorouracil', false);
INSERT INTO request VALUES (38, 'I need Jardiance', true);
INSERT INTO request VALUES (39, 'I need Xtampza ER', false);
INSERT INTO request VALUES (40, 'I need Zinc', false);
INSERT INTO request VALUES (41, 'I need Celecoxib', false);
INSERT INTO request VALUES (42, 'I need Zithromax', false);
INSERT INTO request VALUES (43, 'I need Flagyl', true);
INSERT INTO request VALUES (44, 'I need Dilaudid', false);
INSERT INTO request VALUES (45, 'I need Esomeprazole', false);
INSERT INTO request VALUES (46, 'I need Zometa', true);
INSERT INTO request VALUES (47, 'I need Dextroamphetamine', false);
INSERT INTO request VALUES (48, 'I need Fosfomycin', false);
INSERT INTO request VALUES (49, 'I need Xhance', false);
INSERT INTO request VALUES (50, 'I need Gentamicin ophthalmic', true);
INSERT INTO request VALUES (51, 'I need Clarithromycin', false);
INSERT INTO request VALUES (52, 'I need Divalproex', true);
INSERT INTO request VALUES (53, 'I need Clonidine', false);
INSERT INTO request VALUES (54, 'I need Zonegran', true);
INSERT INTO request VALUES (55, 'I need Amitriptyline', false);
INSERT INTO request VALUES (56, 'I need Aripiprazole', true);
INSERT INTO request VALUES (57, 'I need Risedronate', true);
INSERT INTO request VALUES (58, 'I need Zovirax', true);
INSERT INTO request VALUES (59, 'I need Zoladex', false);
INSERT INTO request VALUES (60, 'I need Doxepin', false);
INSERT INTO request VALUES (61, 'I need Fosinopril', true);
INSERT INTO request VALUES (62, 'I need Jentadueto', false);
INSERT INTO request VALUES (63, 'I need Abilify', true);
INSERT INTO request VALUES (64, 'I need Zarxio', true);
INSERT INTO request VALUES (65, 'I need Estradiol', true);
INSERT INTO request VALUES (66, 'I need Xiaflex', false);
INSERT INTO request VALUES (67, 'I need Glimepiride', false);
INSERT INTO request VALUES (68, 'I need Rifampin', true);
INSERT INTO request VALUES (69, 'I need Fluoxetine', true);
INSERT INTO request VALUES (70, 'I need Biktarvy', false);
INSERT INTO request VALUES (71, 'I need Qvar Redihaler', true);
INSERT INTO request VALUES (72, 'I need Xolair', false);
INSERT INTO request VALUES (73, 'I need Glyburide', false);
INSERT INTO request VALUES (74, 'I need Januvia', false);
INSERT INTO request VALUES (75, 'I need Zomig', true);
INSERT INTO request VALUES (76, 'I need Quinine', false);
INSERT INTO request VALUES (77, 'I need Xyosted', false);
INSERT INTO request VALUES (78, 'I need Zolpidem Tartrate', true);
INSERT INTO request VALUES (79, 'I need Risperdal', true);
INSERT INTO request VALUES (80, 'I need Zaroxolyn', true);
INSERT INTO request VALUES (81, 'I need Amlodipine', false);
INSERT INTO request VALUES (82, 'I need Biaxin', true);
INSERT INTO request VALUES (83, 'I need Xtandi', true);
INSERT INTO request VALUES (84, 'I need Xylitol', false);
INSERT INTO request VALUES (85, 'I need Escitalopram', false);
INSERT INTO request VALUES (86, 'I need Fludrocortisone', true);
INSERT INTO request VALUES (87, 'I need Zofran', false);
INSERT INTO request VALUES (88, 'I need Glipizide and metformin', true);
INSERT INTO request VALUES (89, 'I need Clonazepam', false);
INSERT INTO request VALUES (90, 'I need Calcium carbonate', true);
INSERT INTO request VALUES (91, 'I need Docusate', false);
INSERT INTO request VALUES (92, 'I need Zofran ODT', false);
INSERT INTO request VALUES (93, 'I need Carafate', true);
INSERT INTO request VALUES (94, 'I need Depo-Provera', false);
INSERT INTO request VALUES (95, 'I need Boniva', false);
INSERT INTO request VALUES (96, 'I need Restasis', true);
INSERT INTO request VALUES (97, 'I need Zyloprim', false);
INSERT INTO request VALUES (98, 'I need Atarax', false);
INSERT INTO request VALUES (99, 'I need Quelicin', false);
INSERT INTO request VALUES (100, 'I need Rozerem', true);
INSERT INTO request VALUES (101, 'I need Restoril', false);
INSERT INTO request VALUES (102, 'I need Anastrozole', false);
INSERT INTO request VALUES (103, 'I need Fluconazole', true);
INSERT INTO request VALUES (104, 'I need Xeljanz', true);
INSERT INTO request VALUES (105, 'I need Qsymia', false);
INSERT INTO request VALUES (106, 'I need Bisacodyl', false);
INSERT INTO request VALUES (107, 'I need Qudexy XR', false);
INSERT INTO request VALUES (108, 'I need Alfuzosin', true);
INSERT INTO request VALUES (109, 'I need Budesonide and Formoterol', false);
INSERT INTO request VALUES (110, 'I need Dicyclomine', true);
INSERT INTO request VALUES (111, 'I need Bumetanide', true);
INSERT INTO request VALUES (112, 'I need Cialis', false);
INSERT INTO request VALUES (113, 'I need Ranolazine', false);
INSERT INTO request VALUES (114, 'I need Dupixent', true);
INSERT INTO request VALUES (115, 'I need Botox', true);
INSERT INTO request VALUES (116, 'I need Xylometazoline nasal', false);
INSERT INTO request VALUES (117, 'I need Xylocaine Jelly', false);
INSERT INTO request VALUES (118, 'I need Jynarque', false);
INSERT INTO request VALUES (119, 'I need Amlodipine Besylate', true);
INSERT INTO request VALUES (120, 'I need Bicalutamide', true);
INSERT INTO request VALUES (121, 'I need Amoxicillin and Clavulanate', false);
INSERT INTO request VALUES (122, 'I need Ertapenem', false);
INSERT INTO request VALUES (123, 'I need Enbrel', false);
INSERT INTO request VALUES (124, 'I need Fluticasone and salmeterol', true);
INSERT INTO request VALUES (125, 'I need Jatenzo', false);
INSERT INTO request VALUES (126, 'I need Aricept', true);
INSERT INTO request VALUES (127, 'I need Qbrexza', false);
INSERT INTO request VALUES (128, 'I need Zoledronic acid', true);
INSERT INTO request VALUES (129, 'I need EpiPen', false);
INSERT INTO request VALUES (130, 'I need Rifaximin', true);
INSERT INTO request VALUES (131, 'I need Jiaogulan', true);
INSERT INTO request VALUES (132, 'I need Cozaar', true);
INSERT INTO request VALUES (133, 'I need Diclofenac Sodium', true);
INSERT INTO request VALUES (134, 'I need Rosuvastatin', false);
INSERT INTO request VALUES (135, 'I need Zestoretic', true);
INSERT INTO request VALUES (136, 'I need Renvela', true);
INSERT INTO request VALUES (137, 'I need Felodipine', true);
INSERT INTO request VALUES (138, 'I need Ezetimibe', false);
INSERT INTO request VALUES (139, 'I need Jentadueto XR', true);
INSERT INTO request VALUES (140, 'I need Aleve', false);
INSERT INTO request VALUES (141, 'I need Cephalexin', false);
INSERT INTO request VALUES (142, 'I need Epclusa', true);
INSERT INTO request VALUES (143, 'I need Effexor XR', false);
INSERT INTO request VALUES (144, 'I need Emgality', false);
INSERT INTO request VALUES (145, 'I need Xifaxan', true);
INSERT INTO request VALUES (146, 'I need Bevacizumab', false);
INSERT INTO request VALUES (147, 'I need Brimonidine', true);
INSERT INTO request VALUES (148, 'I need Jublia', false);
INSERT INTO request VALUES (149, 'I need Quetiapine', true);
INSERT INTO request VALUES (150, 'I need Clopidogrel', false);
INSERT INTO request VALUES (151, 'I need Jadenu', false);
INSERT INTO request VALUES (152, 'I need Bethanechol', true);
INSERT INTO request VALUES (153, 'I need Dutasteride', false);
INSERT INTO request VALUES (154, 'I need Cymbalta', false);
INSERT INTO request VALUES (155, 'I need Geodon', false);
INSERT INTO request VALUES (156, 'I need Coreg', false);
INSERT INTO request VALUES (157, 'I need Diltiazem', false);
INSERT INTO request VALUES (158, 'I need Finasteride', true);
INSERT INTO request VALUES (159, 'I need Fluvoxamine', false);
INSERT INTO request VALUES (160, 'I need Flovent', false);
INSERT INTO request VALUES (161, 'I need Actos', false);
INSERT INTO request VALUES (162, 'I need Juleber', true);
INSERT INTO request VALUES (163, 'I need Doxazosin', true);
INSERT INTO request VALUES (164, 'I need Claritin', false);
INSERT INTO request VALUES (165, 'I need Dexilant', false);
INSERT INTO request VALUES (166, 'I need Zoloft', false);
INSERT INTO request VALUES (167, 'I need Qternmet XR', true);
INSERT INTO request VALUES (168, 'I need Diflucan', false);
INSERT INTO request VALUES (169, 'I need Glucagon', false);
INSERT INTO request VALUES (170, 'I need Epidiolex', false);
INSERT INTO request VALUES (171, 'I need Amitiza', false);
INSERT INTO request VALUES (172, 'I need Cilostazol', true);
INSERT INTO request VALUES (173, 'I need Zolmitriptan', true);
INSERT INTO request VALUES (174, 'I need Glycerin', false);
INSERT INTO request VALUES (175, 'I need Xenazine', false);
INSERT INTO request VALUES (176, 'I need Zetia', false);
INSERT INTO request VALUES (177, 'I need Ferrous Sulfate', true);
INSERT INTO request VALUES (178, 'I need Epinephrine', true);
INSERT INTO request VALUES (179, 'I need Eliquis', false);
INSERT INTO request VALUES (180, 'I need Ciprofloxacin', false);
INSERT INTO request VALUES (181, 'I need Colchicine', true);
INSERT INTO request VALUES (182, 'I need Ambien', true);
INSERT INTO request VALUES (183, 'I need Fish Oil', true);
INSERT INTO request VALUES (184, 'I need Azathioprine', false);
INSERT INTO request VALUES (185, 'I need Acetaminophen', false);
INSERT INTO request VALUES (186, 'I need Jornay PM', true);
INSERT INTO request VALUES (187, 'I need Bystolic', false);
INSERT INTO request VALUES (188, 'I need Belsomra', true);
INSERT INTO request VALUES (189, 'I need Xenleta', false);
INSERT INTO request VALUES (190, 'I need Doxycycline', false);
INSERT INTO request VALUES (191, 'I need Xultophy', false);
INSERT INTO request VALUES (192, 'I need Codeine', true);
INSERT INTO request VALUES (193, 'I need Juvederm', false);
INSERT INTO request VALUES (194, 'I need Juluca', false);
INSERT INTO request VALUES (195, 'I need Ginkgo', false);


INSERT INTO chat VALUES (1, 'Chat name');
INSERT INTO chat VALUES (2, 'Chat name');
INSERT INTO chat VALUES (3, 'Chat name');
INSERT INTO chat VALUES (4, 'Chat name');
INSERT INTO chat VALUES (5, 'Chat name');
INSERT INTO chat VALUES (6, 'Chat name');
INSERT INTO chat VALUES (7, 'Chat name');
INSERT INTO chat VALUES (8, 'Chat name');
INSERT INTO chat VALUES (9, 'Chat name');
INSERT INTO chat VALUES (10, 'Chat name');
INSERT INTO chat VALUES (11, 'Chat name');
INSERT INTO chat VALUES (12, 'Chat name');
INSERT INTO chat VALUES (13, 'Chat name');
INSERT INTO chat VALUES (14, 'Chat name');
INSERT INTO chat VALUES (15, 'Chat name');
INSERT INTO chat VALUES (16, 'Chat name');
INSERT INTO chat VALUES (17, 'Chat name');
INSERT INTO chat VALUES (18, 'Chat name');
INSERT INTO chat VALUES (19, 'Chat name');
INSERT INTO chat VALUES (20, 'Chat name');
INSERT INTO chat VALUES (21, 'Chat name');
INSERT INTO chat VALUES (22, 'Chat name');
INSERT INTO chat VALUES (23, 'Chat name');
INSERT INTO chat VALUES (24, 'Chat name');
INSERT INTO chat VALUES (25, 'Chat name');
INSERT INTO chat VALUES (26, 'Chat name');
INSERT INTO chat VALUES (27, 'Chat name');


INSERT INTO message VALUES (1, 7, 10, 'We wee enough wee every month to fill a bath!');
INSERT INTO message VALUES (2, 25, 17, 'The cornea is the only part of the body with no blood supply – it gets its oxygen directly from the air.');
INSERT INTO message VALUES (3, 3, 12, 'The human body contains enough fat to make seven bars of soap.');
INSERT INTO message VALUES (4, 10, 5, 'Embryos develop fingerprints three months after conception.');
INSERT INTO message VALUES (5, 8, 9, 'Between birth and death, the human body goes from having 300 bones, to just 206.');
INSERT INTO message VALUES (6, 27, 7, 'Hearts can beat outside of their bodies.');
INSERT INTO message VALUES (7, 12, 16, 'When you blush, the inside of your stomach does too.');
INSERT INTO message VALUES (8, 6, 15, 'Humans have a “diving reflex” that shuts down bodily functions when submerged in water to prevent drowning.');
INSERT INTO message VALUES (9, 16, 6, 'There are certain kinds of tumors that can grow their own teeth and hair – they’re called teratomas.');
INSERT INTO message VALUES (10, 4, 8, 'Humans are bioluminescent, the light just isn’t perceptible to the human eye.');
INSERT INTO message VALUES (11, 1, 13, 'Astronauts can grow up to two inches taller in space.');
INSERT INTO message VALUES (12, 14, 4, 'Your brain can survive for five to 10 minutes without oxygen.');


INSERT INTO salary VALUES (1, 657145, 3);
INSERT INTO salary VALUES (2, 4778587, 14);
INSERT INTO salary VALUES (3, 4379007, 12);
INSERT INTO salary VALUES (4, 9488349, 6);
INSERT INTO salary VALUES (5, 9172896, 11);
INSERT INTO salary VALUES (6, 763476, 5);
INSERT INTO salary VALUES (7, 8716661, 9);
INSERT INTO salary VALUES (8, 5647694, 1);
INSERT INTO salary VALUES (9, 8464177, 13);
INSERT INTO salary VALUES (10, 3457115, 7);
INSERT INTO salary VALUES (11, 9670617, 10);
INSERT INTO salary VALUES (12, 801359, 18);
INSERT INTO salary VALUES (13, 3796450, 16);
INSERT INTO salary VALUES (14, 8540089, 8);
INSERT INTO salary VALUES (15, 2273945, 2);


INSERT INTO medicament VALUES (1, 'AUXiuQtb05mWyusuc', 'Jakafi', 2);
INSERT INTO medicament VALUES (2, 'ghZIO5pS', 'Glipizide', 3);
INSERT INTO medicament VALUES (3, 'CD6HOViitpSNYvRdOfjIj', 'Revatio', 4);
INSERT INTO medicament VALUES (4, 'WlXe9f37Yopq4BquxhU', 'Eucrisa', 5);
INSERT INTO medicament VALUES (5, '3yNlyN6mFpmiL8OGS1ZW', 'Remicade', 6);
INSERT INTO medicament VALUES (6, 'NaFD3qGdQfLtfb7OcOVpP', 'Zosyn', 7);
INSERT INTO medicament VALUES (7, '9x483fKM', 'Zanaflex', 8);
INSERT INTO medicament VALUES (8, 'X8ebYquoobST', 'Xrylix', 9);
INSERT INTO medicament VALUES (9, '7eXlxGejq7aZ', 'Glucophage', 10);
INSERT INTO medicament VALUES (10, 'lcSmoDVOJyGV', 'Eszopiclone', 11);
INSERT INTO medicament VALUES (11, '6Q1mp31T1VqK8s4iT63SW', 'Glucosamine', 12);
INSERT INTO medicament VALUES (12, 'qeJf06s2RFfhe5eUv', 'Gilenya', 1);
INSERT INTO medicament VALUES (13, 'U4eoO2N5F5ytKFL', 'Atropine', 2);
INSERT INTO medicament VALUES (14, 'FtDp5CGggetoyUoDkq', 'Xpovio', 3);
INSERT INTO medicament VALUES (15, 'oND8LdFjnnsWKXrK', 'Advair Diskus', 4);
INSERT INTO medicament VALUES (16, '6qE32DrfAUt5u0L', 'Fluticasone Propionate', 5);
INSERT INTO medicament VALUES (17, '199pJ5S7', 'Donepezil', 6);
INSERT INTO medicament VALUES (18, 'MsLd9tfROugTy3aSQJB1', 'Diazepam', 7);
INSERT INTO medicament VALUES (19, '8arKmAHQpKkW96YaCXR9efYT', 'Bentyl', 8);
INSERT INTO medicament VALUES (20, 'uydtFzFjQJ8h', 'Questran Light', 9);
INSERT INTO medicament VALUES (21, 'IoW8Yf8ZpxFCQ', 'GoLYTELY', 10);
INSERT INTO medicament VALUES (22, 'LiOpoqmU74SJXOy', 'Estrace', 11);
INSERT INTO medicament VALUES (23, 'GFQUCL7jM', 'Duloxetine', 12);
INSERT INTO medicament VALUES (24, 'j6h4hSbfIEH54sxSp', 'Quinidine Sulfate', 1);
INSERT INTO medicament VALUES (25, 'P7fnhHRRf9ZCAdxWA', 'Chlorthalidone', 2);
INSERT INTO medicament VALUES (26, 'gRaX6LBaV42Lc0MXOl7q05Q', 'Xeomin', 3);
INSERT INTO medicament VALUES (27, 'tZVby5GB', 'Relpax', 4);
INSERT INTO medicament VALUES (28, 'MIFQya61', 'Ferrous gluconate', 5);
INSERT INTO medicament VALUES (29, 'zg5BRIPo5y2NqMW6Z6GlrJ', 'Benadryl', 6);
INSERT INTO medicament VALUES (30, '3oURpVJDK7hyRicu', 'Xadago', 7);
INSERT INTO medicament VALUES (31, 'rYTpDTjB9WRTmVJjq1rV6Ua', 'Formoterol', 8);
INSERT INTO medicament VALUES (32, 'fGKcOCcfWTDLj', 'Glycopyrrolate', 9);
INSERT INTO medicament VALUES (33, 'kUvzff5q5myr6GlOXXbo2Z3F', 'Farxiga', 10);
INSERT INTO medicament VALUES (34, 'apd54e1FG62Y63Utnxtl', 'Rocephin', 11);
INSERT INTO medicament VALUES (35, '59qG6HyO', 'Jevtana', 12);
INSERT INTO medicament VALUES (36, '2EgC29itIQ', 'Xopenex HFA', 1);
INSERT INTO medicament VALUES (37, 'P5DKu1L24F07VVcdH', 'Griseofulvin', 2);
INSERT INTO medicament VALUES (38, 'lpUy3xvB1O68LDW4', 'Xarelto', 3);
INSERT INTO medicament VALUES (39, 'vpoq8HmoxPpRXNnsM6PESx', 'Erythromycin', 4);
INSERT INTO medicament VALUES (40, 'xHsE7FJEy7uLqJOH8', 'Adderall', 5);
INSERT INTO medicament VALUES (41, 'VKcBAxIq8bC4Oc', 'Alendronate', 6);
INSERT INTO medicament VALUES (42, 'KEJ6NP4bESvyfhuMF6Kv9o', 'Exforge', 7);
INSERT INTO medicament VALUES (43, 'X5X7hY2HeWRUMkT32s', 'Atorvastatin', 8);
INSERT INTO medicament VALUES (44, 'rCmE4ReuoCjORtrt', 'Rituxan', 9);
INSERT INTO medicament VALUES (45, 'PxD44vK2K8hZpC', 'Digoxin', 10);
INSERT INTO medicament VALUES (46, '5GcHPIDgAaMm', 'Evista', 11);
INSERT INTO medicament VALUES (47, 'Zj6IpC4BQKx894sq36s5', 'Ritalin', 12);
INSERT INTO medicament VALUES (48, 'MbiLGfR2CmBF7voNQ', 'Ephedrine', 1);
INSERT INTO medicament VALUES (49, '86Q8cUmUiOezapWuJ5W1', 'Focalin', 2);
INSERT INTO medicament VALUES (50, 'Z6drP9dy7ylqk', 'Xerese', 3);
INSERT INTO medicament VALUES (51, 'uyOuNeVCfcdpnygzpry', 'Florastor', 4);
INSERT INTO medicament VALUES (52, 'ToHnHh26U4JNO', 'Rexulti', 5);
INSERT INTO medicament VALUES (53, 'ArUcvoq6ufqrNumD', 'Breo Ellipta', 6);
INSERT INTO medicament VALUES (54, 'uP1Ptu2e7nH', 'Aspirin', 7);
INSERT INTO medicament VALUES (55, 'vUWklUn95gsxPWBsMuOUQsxn', 'Diphenhydramine', 8);
INSERT INTO medicament VALUES (56, 'pigiPhM6', 'Glucose', 9);
INSERT INTO medicament VALUES (57, 'eKto4pBId8Ok8cV', 'Quasense', 10);
INSERT INTO medicament VALUES (58, 'TGUVUUyQfv4', 'Xenical', 11);
INSERT INTO medicament VALUES (59, 'bAXPEL1c3Xm6zlW0', 'Buprenorphine and Naloxone', 12);
INSERT INTO medicament VALUES (60, '3Fv3VXWBgDpgubPm16G', 'Febuxostat', 1);
INSERT INTO medicament VALUES (61, 'vVCNiEQ8776D', 'Crestor', 2);
INSERT INTO medicament VALUES (62, 'kZ4qQqNaDfcgtM', 'Xiidra', 3);
INSERT INTO medicament VALUES (63, 'BJrMkuRmA', 'Citalopram', 4);
INSERT INTO medicament VALUES (64, 'z1ymt1jkD', 'Ginger', 5);
INSERT INTO medicament VALUES (65, 'l6nEXP5Qb', 'Granisetron', 6);
INSERT INTO medicament VALUES (66, 'Yg2pXkdOxDVJgP3Rl6ztXYv', 'Junel 1/20', 7);
INSERT INTO medicament VALUES (67, 'kZFq7b81zJPUd7CCLdNo', 'Fentanyl', 8);
INSERT INTO medicament VALUES (68, 'aKuYMjniTKvWn5V5W', 'Advil', 9);
INSERT INTO medicament VALUES (69, 'yzlZaJ0IeIVQsnzWD', 'Quinidine', 10);
INSERT INTO medicament VALUES (70, 'uuSRQBAEPdlKHbk5', 'Ramipril', 11);
INSERT INTO medicament VALUES (71, '5zEtDmWogS5oY124', 'Quercetin', 12);
INSERT INTO medicament VALUES (72, 'TT8mxc1CtbuvX4MP0eAy4eYu', 'Ditropan', 1);
INSERT INTO medicament VALUES (73, 'ZcE3BHVqpbJc', 'Cefdinir', 2);
INSERT INTO medicament VALUES (74, 'Cu5vQTrJ', 'Femara', 3);
INSERT INTO medicament VALUES (75, '2ChztWr7f8L97', 'Xalkori', 4);
INSERT INTO medicament VALUES (76, 'bmUX9jbIll4do', 'Zyprexa', 5);
INSERT INTO medicament VALUES (77, 'FbsiTkOZYLxLgKm2pTx', 'Coumadin', 6);
INSERT INTO medicament VALUES (78, 'PQhiCRgs', 'Buspirone', 7);
INSERT INTO medicament VALUES (79, 'QzkoUM65SBbug', 'Augmentin', 8);
INSERT INTO medicament VALUES (80, '47hUZzuXWDOp', 'Xylocaine', 9);
INSERT INTO medicament VALUES (81, 'vBIvTP8EWs', 'Amiodarone', 10);
INSERT INTO medicament VALUES (82, 'Mi0ZYK4rDYPScFfG', 'Jencycla', 11);
INSERT INTO medicament VALUES (83, 'OUpfW4WH', 'Ceftriaxone', 12);
INSERT INTO medicament VALUES (84, 'WZ9l6HvkHNdyjWdi6gJYxBK4', 'Ascorbic acid', 1);
INSERT INTO medicament VALUES (85, 'HsT8C8gU9XrI59', 'Genvoya', 2);
INSERT INTO medicament VALUES (86, '0cZxGOsddbU', 'Entyvio', 3);
INSERT INTO medicament VALUES (87, 'giukFHHFCtR9zgv5', 'Flonase', 4);
INSERT INTO medicament VALUES (88, '1W1E9xIbmmL0', 'Ecotrin', 5);
INSERT INTO medicament VALUES (89, 'YHvBXehq5OB37S9fgoNb2em', 'Exelon', 6);
INSERT INTO medicament VALUES (90, 'KFnxFmi75ck08dDSfNa', 'Xgeva', 7);
INSERT INTO medicament VALUES (91, 'NrQv3YqIbUKS7Qzhbt', 'Domperidone', 8);
INSERT INTO medicament VALUES (92, 'emXIaCh0bRJ', 'Cipro', 9);
INSERT INTO medicament VALUES (93, 'eJFNzDurvicjsZ24Ncg3', 'Cholecalciferol', 10);
INSERT INTO medicament VALUES (94, 'MEsFyl0u', 'Bismuth subsalicylate', 11);
INSERT INTO medicament VALUES (95, 'YMYOAuPPoSiqueMIeLy7jk', 'Zyvox', 12);
INSERT INTO medicament VALUES (96, 'ykpVZ9X6ghL2', 'Colace', 1);
INSERT INTO medicament VALUES (97, 'H6UmJiCVzm4DnSeL4', 'Acetaminophen and Hydrocodone', 2);
INSERT INTO medicament VALUES (98, 'XjznfE9BXH7spTOd1kqObkr', 'Aldactone', 3);
INSERT INTO medicament VALUES (99, 'DZ1VRKInQhpuUVQUan', 'Depakote', 4);
INSERT INTO medicament VALUES (100, 'nHZBhXGs01b1PcJfn', 'Clotrimazole', 5);
INSERT INTO medicament VALUES (101, 'rH9oQbvD8ZMB475Q', 'Buspar', 6);
INSERT INTO medicament VALUES (102, 'acgYDqLuh9JTALy', 'Diovan', 7);
INSERT INTO medicament VALUES (103, 'x0jm9s1OP', 'Cefuroxime', 8);
INSERT INTO medicament VALUES (104, 'pJnJedSZpXjzGJJno', 'QNASL', 9);
INSERT INTO medicament VALUES (105, 'Q5z3egd2Vg9j', 'Ginseng', 10);
INSERT INTO medicament VALUES (106, 'o8mpuYQPnkUIP4hv3EPiFN', 'Calcitriol', 11);
INSERT INTO medicament VALUES (107, '0l1VhzyKbtR1qoZl3TZIVk', 'Captopril', 12);
INSERT INTO medicament VALUES (108, 'NXD115ipl8', 'Junel Fe 1/20', 1);
INSERT INTO medicament VALUES (109, 'JsoIEj0dsVB05luhjHTmtAc', 'Zaditor', 2);
INSERT INTO medicament VALUES (110, 'vIQoImrvuqmIi3Sdt5hmQMP0', 'Repaglinide', 3);
INSERT INTO medicament VALUES (111, 'd1Ubgs5vnc146tY', 'Glucotrol', 4);
INSERT INTO medicament VALUES (112, '0iaxpGzVfCmlij0', 'Jolivette', 5);
INSERT INTO medicament VALUES (113, 'p32m6iX3a', 'Atenolol', 6);
INSERT INTO medicament VALUES (114, 'YEXMoFfT5ndpH', 'Ranitidine', 7);
INSERT INTO medicament VALUES (115, 'ZiaytlTEFdjfYe', 'Relafen', 8);
INSERT INTO medicament VALUES (116, 'iCMdHRuR3xC', 'Gralise', 9);
INSERT INTO medicament VALUES (117, 'Wp48YSCY4Nql', 'Albuterol', 10);
INSERT INTO medicament VALUES (118, 'BAbByTTBfcY7flXbm2N9xjF3', 'Clindamycin', 11);
INSERT INTO medicament VALUES (119, '5uyx1phvBkc41RvIO9HM3rE4', 'Acyclovir', 12);
INSERT INTO medicament VALUES (120, 'MdhpmJhFo8ZikCphOzVpNn', 'Jolessa', 1);
INSERT INTO medicament VALUES (121, 'LLm7C8kt', 'Xeljanz XR', 2);
INSERT INTO medicament VALUES (122, '0K5uZ5RmOBu2gxv', 'Denosumab', 3);
INSERT INTO medicament VALUES (123, 'pnOYmA9qy5SKeoOWorAHCmzS', 'Xeloda', 4);
INSERT INTO medicament VALUES (124, 'y5NX9XDi2LjSoeb9', 'Juxtapid', 5);
INSERT INTO medicament VALUES (125, 'XDXWjXLz', 'Qutenza', 6);
INSERT INTO medicament VALUES (126, 'JKWoXzXamYW06Y', 'Flecainide', 7);
INSERT INTO medicament VALUES (127, 'lxcNIBlQM6HV07qVT', 'Dulera', 8);
INSERT INTO medicament VALUES (128, 'YjtYuQXivQurXGcgC', 'Guanfacine', 9);
INSERT INTO medicament VALUES (129, 'YARE9Kzc14k3lPXK6q6', 'Fioricet', 10);
INSERT INTO medicament VALUES (130, 'z7oPfnHiy6D4dz', 'Gleevec', 11);
INSERT INTO medicament VALUES (131, 'ozc5tpvTPVQvcGQpHm2', 'Gabapentin', 12);
INSERT INTO medicament VALUES (132, 'L8QF4d6khMivrxleNQeL', 'Zebeta', 1);
INSERT INTO medicament VALUES (133, 'mSr1YZvs', 'Betamethasone', 2);
INSERT INTO medicament VALUES (134, 'ChoWrubJK8N', 'Bacitracin', 3);
INSERT INTO medicament VALUES (135, 'B4JLAUNO', 'Junel', 4);
INSERT INTO medicament VALUES (136, 'tK46WzmriEx59pCT', 'Cetirizine', 5);
INSERT INTO medicament VALUES (137, 'fz1vPlqLzoNsOYTHVk', 'Xyzal', 6);
INSERT INTO medicament VALUES (138, 'ypqJf6uhsfj', 'Concerta', 7);
INSERT INTO medicament VALUES (139, 'Sfhazsb1bPD09pnk', 'Ropinirole', 8);
INSERT INTO medicament VALUES (140, 'SZIzz26afRaWn', 'Azithromycin', 9);
INSERT INTO medicament VALUES (141, 'oLYjfy5votOTvHDokpR6ARkc', 'Quazepam', 10);
INSERT INTO medicament VALUES (142, 'UhvZLpBYj18DLMS', 'Folic Acid', 11);
INSERT INTO medicament VALUES (143, 'HVOiEeGC1VZ', 'Ranexa', 12);
INSERT INTO medicament VALUES (144, 'gjK4yYGfvIcBGbveGlBQ0BDR', 'Jadelle', 1);
INSERT INTO medicament VALUES (145, 'uVlRmbmPJTBD', 'Robaxin', 2);
INSERT INTO medicament VALUES (146, 'g7eyirVHjdOSvICVvjEIE40', 'Carvedilol', 3);
INSERT INTO medicament VALUES (147, 'ArlbR9JcSJXz', 'Xofigo', 4);
INSERT INTO medicament VALUES (148, 'G0gqRdjzh2LQ9SDmttQSk5', 'Zyrtec', 5);
INSERT INTO medicament VALUES (149, 'sAaacdipTO62X', 'Qbrelis', 6);
INSERT INTO medicament VALUES (150, 'veD9Hqjl', 'Quinine Sulfate', 7);
INSERT INTO medicament VALUES (151, 'SN625QQ73', 'QuilliChew ER', 8);
INSERT INTO medicament VALUES (152, 'CBfmpJvMtpm', 'Quinapril', 9);
INSERT INTO medicament VALUES (153, '6U7YfV2riv3xtcQzpUgoY', 'Flovent HFA', 10);
INSERT INTO medicament VALUES (154, 'uOA9rtCkz5FFZyd', 'Xopenex', 11);
INSERT INTO medicament VALUES (155, 'BdZzRqWHSibs5msk', 'Roxicodone', 12);
INSERT INTO medicament VALUES (156, 'zE7AFJBMnI4O775HRrWKl', 'Zolpidem', 1);
INSERT INTO medicament VALUES (157, '1gUd7i7k3JLa4HyJTvdML', 'Ativan', 2);
INSERT INTO medicament VALUES (158, 'fJFVSaoTzkPG0XvilXd9sj', 'Ginkgo biloba', 3);
INSERT INTO medicament VALUES (159, 'oXuS2Im4uBThbaqR', 'Carbamazepine', 4);
INSERT INTO medicament VALUES (160, 'etQnmjh7QBCn5rxxOpWW2fxC', 'Entresto', 5);
INSERT INTO medicament VALUES (161, '2qUvp2a6NprBlFunojxR', 'Apixaban', 6);
INSERT INTO medicament VALUES (162, '2tQiKDpOJfOOxmJOI9R4khpT', 'Garlic', 7);
INSERT INTO medicament VALUES (163, 'oJhO6lUSLvuK2dNCRvUlMlx', 'Remeron', 8);
INSERT INTO medicament VALUES (164, 'PyPrmiVYpKWpzs3WidG', 'Azelastine', 9);
INSERT INTO medicament VALUES (165, 'OW8t3ktEV56P', 'Dilantin', 10);
INSERT INTO medicament VALUES (166, 'YIYL46jttIbNUS', 'Benztropine', 11);
INSERT INTO medicament VALUES (167, 'P3SaRIJoaEYYjk', 'Elidel', 12);
INSERT INTO medicament VALUES (168, 'ZIQcvzcr', 'Janumet XR', 1);
INSERT INTO medicament VALUES (169, 'lpPb71cHWllC8XZ', 'Zantac', 2);
INSERT INTO medicament VALUES (170, 'IVzA9YCZkmmN', 'Zaleplon', 3);
INSERT INTO medicament VALUES (171, 'rDOUeX3n65nRzDkHIO6F', 'Xofluza', 4);
INSERT INTO medicament VALUES (172, 'brKJqdG6XV', 'Jetrea', 5);
INSERT INTO medicament VALUES (173, '3OXq5BnbuQJ', 'Xylometazoline', 6);
INSERT INTO medicament VALUES (174, 'TeJhdEDVULVBUk0xLv4Zd', 'Zinc sulfate', 7);
INSERT INTO medicament VALUES (175, 'GZEqWDgVyGKHEG2c', 'Basaglar', 8);
INSERT INTO medicament VALUES (176, 'zzPP1nkvj3t1m5BMIR5', 'Bactroban', 9);
INSERT INTO medicament VALUES (177, 'eoMgDbEslLHooRuRZmZq', 'Dyazide', 10);
INSERT INTO medicament VALUES (178, 'RkkcS4AiKhRZ40C8h2s', 'Rituximab', 11);
INSERT INTO medicament VALUES (179, '2mQoNPKgRtNiG', 'Baclofen', 12);
INSERT INTO medicament VALUES (180, 'hZelJsCGmFsUQ', 'Zostavax', 1);
INSERT INTO medicament VALUES (181, 'XpYnI06yiiLLCz', 'Xanax XR', 2);
INSERT INTO medicament VALUES (182, '5k8MalaBkDdX0V9', 'Zenpep', 3);
INSERT INTO medicament VALUES (183, 'EvqTTqCQz', 'DuoNeb', 4);
INSERT INTO medicament VALUES (184, 'EWBGKgB7XrIZmR823klWJqY', 'Enalapril', 5);
INSERT INTO medicament VALUES (185, 'f336GaWIO3YMNK', 'Zestril', 6);
INSERT INTO medicament VALUES (186, 'LVl9EpZJcPCOZEpRht0', 'Robitussin', 7);
INSERT INTO medicament VALUES (187, 'p3kevzAuPbSAzaN', 'Zytiga', 8);
INSERT INTO medicament VALUES (188, 'imKzj5tsdbWj', 'ZTlido', 9);
INSERT INTO medicament VALUES (189, 'Arvm0jUGjyBXJ4r', 'Xulane', 10);
INSERT INTO medicament VALUES (190, 'bb1sCvoZ8uu4OJ', 'Diclofenac', 11);
INSERT INTO medicament VALUES (191, 'GfEXFE9qgfxo6I4U4CqZBn', 'Rivaroxaban', 12);
INSERT INTO medicament VALUES (192, 'uy5yMIKb10cLKx6JfbxFFOCW', 'Gardasil', 1);
INSERT INTO medicament VALUES (193, 'HVlB7LMyGHif7msPpA78qN7H', 'Focalin XR', 2);
INSERT INTO medicament VALUES (194, 'HHpC743zcc6', 'Glyxambi', 3);
INSERT INTO medicament VALUES (195, 'ZYiG8z3akHxdU', 'Dextromethorphan', 4);
INSERT INTO medicament VALUES (196, 'jI9NvhQ7e3vVQTFp', 'Eplerenone', 5);
INSERT INTO medicament VALUES (197, 'OhYH7MHppgn7QKi9', 'Docusate Sodium', 6);
INSERT INTO medicament VALUES (198, '2YgBNbatcoau7A4nA', 'Quixin', 7);
INSERT INTO medicament VALUES (199, '63pZLlVn5gc6TbVuy', 'Zonisamide', 8);
INSERT INTO medicament VALUES (200, 'sriI5Vi4', 'Fluzone', 9);
INSERT INTO medicament VALUES (201, 'GhqGVZNNIGn7Gn3bVLWp', 'Excedrin', 10);
INSERT INTO medicament VALUES (202, '8OAfNuqyECTbc1XZUK27Y6JW', 'Fluticasone', 11);
INSERT INTO medicament VALUES (203, 'l5nGEGSV', 'Bactrim DS', 12);
INSERT INTO medicament VALUES (204, '0zQe9ISpn', 'Ethambutol', 1);
INSERT INTO medicament VALUES (205, 'kEMZAmcvpfvvRSSG9YoizyKf', 'Gemfibrozil', 2);
INSERT INTO medicament VALUES (206, '3RChBih9BuinYr56G', 'Jinteli', 3);
INSERT INTO medicament VALUES (207, '2Cz7uNT0UudtaIG4liM57', 'Desvenlafaxine', 4);
INSERT INTO medicament VALUES (208, 'xAKLeWrnlAgx', 'Xyrem', 5);
INSERT INTO medicament VALUES (209, 'zo46dEW2yQrY48LXUN1DXo1', 'Fenofibrate', 6);
INSERT INTO medicament VALUES (210, 'ntQSVKViz', 'Elmiron', 7);
INSERT INTO medicament VALUES (211, 'qK5HakAxP', 'Ziac', 8);
INSERT INTO medicament VALUES (212, 'C9bVy6Kj5lC', 'Xigduo XR', 9);
INSERT INTO medicament VALUES (213, '8tGUuZ0eIINullv1ibCZrOL', 'Bisoprolol', 10);
INSERT INTO medicament VALUES (214, 'MtQdC7LoJidgI', 'Quillivant XR', 11);
INSERT INTO medicament VALUES (215, 'hea0fxpHlWGOXlV', 'Q-Pap', 12);
INSERT INTO medicament VALUES (216, 'cvRSgZldy0WZ', 'Requip', 1);
INSERT INTO medicament VALUES (217, 'eNck5qhJUon6hPtyJlE', 'Glutathione', 2);
INSERT INTO medicament VALUES (218, 'ImxDHl57l', 'Qualaquin', 3);
INSERT INTO medicament VALUES (219, 'msNiN6A4Xp1nIPK4bzD', 'Galantamine', 4);
INSERT INTO medicament VALUES (220, 'AvElcCmPr', 'Amoxicillin', 5);
INSERT INTO medicament VALUES (221, 'bcUGxcHvNV7pDpnrcA', 'Eligard', 6);
INSERT INTO medicament VALUES (222, '3LEKOyqyxZENe', 'GlycoLax', 7);
INSERT INTO medicament VALUES (223, 'TYTFcqtiKy7Z5j4hSc8Ak8KE', 'Xalatan', 8);
INSERT INTO medicament VALUES (224, '55XA3ayX4z1CsHMnPUGJEaMH', 'Raloxifene', 9);
INSERT INTO medicament VALUES (225, 'GLKNM1TzXEZtxFiKslmVzf3G', 'Gaviscon', 10);
INSERT INTO medicament VALUES (226, '9r8ONJME61H6s', 'Benazepril', 11);


INSERT INTO supply VALUES  (1, 'table', 2);
INSERT INTO supply VALUES  (2, 'table', 3);
INSERT INTO supply VALUES  (3, 'table', 4);
INSERT INTO supply VALUES  (4, 'table', 5);
INSERT INTO supply VALUES  (5, 'table', 6);
INSERT INTO supply VALUES  (6, 'table', 7);
INSERT INTO supply VALUES  (7, 'table', 8);
INSERT INTO supply VALUES  (8, 'table', 9);
INSERT INTO supply VALUES  (9, 'table', 10);
INSERT INTO supply VALUES  (10, 'table', 11);
INSERT INTO supply VALUES  (11, 'table', 12);
INSERT INTO supply VALUES  (12, 'table', 1);
INSERT INTO supply VALUES  (13, 'table', 2);
INSERT INTO supply VALUES  (14, 'table', 3);
INSERT INTO supply VALUES  (15, 'table', 4);
INSERT INTO supply VALUES  (16, 'table', 5);
INSERT INTO supply VALUES  (17, 'table', 6);
INSERT INTO supply VALUES  (18, 'table', 7);
INSERT INTO supply VALUES  (19, 'table', 8);
INSERT INTO supply VALUES  (20, 'table', 9);
INSERT INTO supply VALUES  (21, 'table', 10);
INSERT INTO supply VALUES  (22, 'table', 11);
INSERT INTO supply VALUES  (23, 'table', 12);
INSERT INTO supply VALUES  (24, 'table', 1);
INSERT INTO supply VALUES  (25, 'table', 2);
INSERT INTO supply VALUES  (26, 'table', 3);
INSERT INTO supply VALUES  (27, 'table', 4);
INSERT INTO supply VALUES  (28, 'table', 5);
INSERT INTO supply VALUES  (29, 'table', 6);
INSERT INTO supply VALUES  (30, 'table', 7);
INSERT INTO supply VALUES  (31, 'table', 8);
INSERT INTO supply VALUES  (32, 'table', 9);
INSERT INTO supply VALUES  (33, 'table', 10);
INSERT INTO supply VALUES  (34, 'table', 11);
INSERT INTO supply VALUES  (35, 'table', 12);
INSERT INTO supply VALUES  (36, 'table', 1);
INSERT INTO supply VALUES  (37, 'table', 2);
INSERT INTO supply VALUES  (38, 'table', 3);
INSERT INTO supply VALUES  (39, 'table', 4);
INSERT INTO supply VALUES  (40, 'table', 5);
INSERT INTO supply VALUES  (41, 'table', 6);
INSERT INTO supply VALUES  (42, 'table', 7);
INSERT INTO supply VALUES  (43, 'table', 8);
INSERT INTO supply VALUES  (44, 'table', 9);
INSERT INTO supply VALUES  (45, 'table', 10);
INSERT INTO supply VALUES  (46, 'table', 11);
INSERT INTO supply VALUES  (47, 'table', 12);
INSERT INTO supply VALUES  (48, 'table', 1);
INSERT INTO supply VALUES  (49, 'table', 2);
INSERT INTO supply VALUES  (50, 'table', 3);
INSERT INTO supply VALUES  (51, 'table', 4);
INSERT INTO supply VALUES  (52, 'table', 5);
INSERT INTO supply VALUES  (53, 'table', 6);
INSERT INTO supply VALUES  (54, 'table', 7);
INSERT INTO supply VALUES  (55, 'table', 8);
INSERT INTO supply VALUES  (56, 'table', 9);
INSERT INTO supply VALUES  (57, 'table', 10);
INSERT INTO supply VALUES  (58, 'table', 11);
INSERT INTO supply VALUES  (59, 'table', 12);
INSERT INTO supply VALUES  (60, 'table', 1);
INSERT INTO supply VALUES  (61, 'table', 2);
INSERT INTO supply VALUES  (62, 'table', 3);
INSERT INTO supply VALUES  (63, 'table', 4);
INSERT INTO supply VALUES  (64, 'table', 5);
INSERT INTO supply VALUES  (65, 'table', 6);
INSERT INTO supply VALUES  (66, 'table', 7);
INSERT INTO supply VALUES  (67, 'table', 8);
INSERT INTO supply VALUES  (68, 'table', 9);
INSERT INTO supply VALUES  (69, 'table', 10);
INSERT INTO supply VALUES  (70, 'table', 11);
INSERT INTO supply VALUES  (71, 'table', 12);
INSERT INTO supply VALUES  (72, 'table', 1);
INSERT INTO supply VALUES  (73, 'table', 2);
INSERT INTO supply VALUES  (74, 'table', 3);
INSERT INTO supply VALUES  (75, 'table', 4);
INSERT INTO supply VALUES  (76, 'table', 5);
INSERT INTO supply VALUES  (77, 'table', 6);
INSERT INTO supply VALUES  (78, 'table', 7);
INSERT INTO supply VALUES  (79, 'table', 8);
INSERT INTO supply VALUES  (80, 'table', 9);
INSERT INTO supply VALUES  (81, 'table', 10);
INSERT INTO supply VALUES  (82, 'table', 11);
INSERT INTO supply VALUES  (83, 'table', 12);
INSERT INTO supply VALUES  (84, 'table', 1);
INSERT INTO supply VALUES  (85, 'table', 2);
INSERT INTO supply VALUES  (86, 'table', 3);
INSERT INTO supply VALUES  (87, 'table', 4);
INSERT INTO supply VALUES  (88, 'table', 5);
INSERT INTO supply VALUES  (89, 'table', 6);
INSERT INTO supply VALUES  (90, 'table', 7);
INSERT INTO supply VALUES  (91, 'table', 8);
INSERT INTO supply VALUES  (92, 'table', 9);
INSERT INTO supply VALUES  (93, 'table', 10);
INSERT INTO supply VALUES  (94, 'table', 11);
INSERT INTO supply VALUES  (95, 'table', 12);
INSERT INTO supply VALUES  (96, 'table', 1);
INSERT INTO supply VALUES  (97, 'table', 2);
INSERT INTO supply VALUES  (98, 'table', 3);
INSERT INTO supply VALUES  (99, 'table', 4);
INSERT INTO supply VALUES  (100, 'table', 5);
INSERT INTO supply VALUES  (101, 'table', 6);
INSERT INTO supply VALUES  (102, 'table', 7);
INSERT INTO supply VALUES  (103, 'table', 8);
INSERT INTO supply VALUES  (104, 'table', 9);
INSERT INTO supply VALUES  (105, 'table', 10);
INSERT INTO supply VALUES  (106, 'table', 11);
INSERT INTO supply VALUES  (107, 'table', 12);
INSERT INTO supply VALUES  (108, 'table', 1);
INSERT INTO supply VALUES  (109, 'table', 2);
INSERT INTO supply VALUES  (110, 'table', 3);
INSERT INTO supply VALUES  (111, 'table', 4);
INSERT INTO supply VALUES  (112, 'table', 5);
INSERT INTO supply VALUES  (113, 'table', 6);
INSERT INTO supply VALUES  (114, 'table', 7);
INSERT INTO supply VALUES  (115, 'table', 8);
INSERT INTO supply VALUES  (116, 'table', 9);
INSERT INTO supply VALUES  (117, 'table', 10);
INSERT INTO supply VALUES  (118, 'table', 11);
INSERT INTO supply VALUES  (119, 'table', 12);
INSERT INTO supply VALUES  (120, 'table', 1);
INSERT INTO supply VALUES  (121, 'table', 2);
INSERT INTO supply VALUES  (122, 'table', 3);
INSERT INTO supply VALUES  (123, 'table', 4);
INSERT INTO supply VALUES  (124, 'table', 5);
INSERT INTO supply VALUES  (125, 'table', 6);
INSERT INTO supply VALUES  (126, 'table', 7);
INSERT INTO supply VALUES  (127, 'table', 8);
INSERT INTO supply VALUES  (128, 'table', 9);
INSERT INTO supply VALUES  (129, 'table', 10);
INSERT INTO supply VALUES  (130, 'table', 11);
INSERT INTO supply VALUES  (131, 'table', 12);
INSERT INTO supply VALUES  (132, 'table', 1);
INSERT INTO supply VALUES  (133, 'table', 2);
INSERT INTO supply VALUES  (134, 'table', 3);
INSERT INTO supply VALUES  (135, 'table', 4);
INSERT INTO supply VALUES  (136, 'table', 5);
INSERT INTO supply VALUES  (137, 'table', 6);
INSERT INTO supply VALUES  (138, 'table', 7);
INSERT INTO supply VALUES  (139, 'table', 8);
INSERT INTO supply VALUES  (140, 'table', 9);
INSERT INTO supply VALUES  (141, 'table', 10);
INSERT INTO supply VALUES  (142, 'table', 11);
INSERT INTO supply VALUES  (143, 'table', 12);
INSERT INTO supply VALUES  (144, 'table', 1);
INSERT INTO supply VALUES  (145, 'table', 2);
INSERT INTO supply VALUES  (146, 'table', 3);
INSERT INTO supply VALUES  (147, 'table', 4);
INSERT INTO supply VALUES  (148, 'table', 5);
INSERT INTO supply VALUES  (149, 'table', 6);
INSERT INTO supply VALUES  (150, 'table', 7);
INSERT INTO supply VALUES  (151, 'table', 8);
INSERT INTO supply VALUES  (152, 'table', 9);
INSERT INTO supply VALUES  (153, 'table', 10);
INSERT INTO supply VALUES  (154, 'table', 11);
INSERT INTO supply VALUES  (155, 'table', 12);
INSERT INTO supply VALUES  (156, 'table', 1);
INSERT INTO supply VALUES  (157, 'table', 2);
INSERT INTO supply VALUES  (158, 'table', 3);
INSERT INTO supply VALUES  (159, 'table', 4);
INSERT INTO supply VALUES  (160, 'table', 5);
INSERT INTO supply VALUES  (161, 'table', 6);
INSERT INTO supply VALUES  (162, 'table', 7);
INSERT INTO supply VALUES  (163, 'table', 8);
INSERT INTO supply VALUES  (164, 'table', 9);
INSERT INTO supply VALUES  (165, 'table', 10);
INSERT INTO supply VALUES  (166, 'table', 11);
INSERT INTO supply VALUES  (167, 'table', 12);
INSERT INTO supply VALUES  (168, 'table', 1);
INSERT INTO supply VALUES  (169, 'table', 2);
INSERT INTO supply VALUES  (170, 'table', 3);
INSERT INTO supply VALUES  (171, 'table', 4);
INSERT INTO supply VALUES  (172, 'table', 5);
INSERT INTO supply VALUES  (173, 'table', 6);
INSERT INTO supply VALUES  (174, 'table', 7);
INSERT INTO supply VALUES  (175, 'table', 8);
INSERT INTO supply VALUES  (176, 'table', 9);
INSERT INTO supply VALUES  (177, 'table', 10);
INSERT INTO supply VALUES  (178, 'table', 11);
INSERT INTO supply VALUES  (179, 'table', 12);
INSERT INTO supply VALUES  (180, 'table', 1);
INSERT INTO supply VALUES  (181, 'table', 2);
INSERT INTO supply VALUES  (182, 'table', 3);
INSERT INTO supply VALUES  (183, 'table', 4);
INSERT INTO supply VALUES  (184, 'table', 5);
INSERT INTO supply VALUES  (185, 'table', 6);
INSERT INTO supply VALUES  (186, 'table', 7);
INSERT INTO supply VALUES  (187, 'table', 8);
INSERT INTO supply VALUES  (188, 'table', 9);
INSERT INTO supply VALUES  (189, 'table', 10);
INSERT INTO supply VALUES  (190, 'table', 11);
INSERT INTO supply VALUES  (191, 'table', 12);
INSERT INTO supply VALUES  (192, 'table', 1);
INSERT INTO supply VALUES  (193, 'table', 2);
INSERT INTO supply VALUES  (194, 'table', 3);
INSERT INTO supply VALUES  (195, 'table', 4);
INSERT INTO supply VALUES  (196, 'table', 5);
INSERT INTO supply VALUES  (197, 'table', 6);
INSERT INTO supply VALUES  (198, 'table', 7);
INSERT INTO supply VALUES  (199, 'table', 8);
INSERT INTO supply VALUES  (200, 'table', 9);
INSERT INTO supply VALUES  (201, 'table', 10);
INSERT INTO supply VALUES  (202, 'table', 11);
INSERT INTO supply VALUES  (203, 'table', 12);
INSERT INTO supply VALUES  (204, 'table', 1);
INSERT INTO supply VALUES  (205, 'table', 2);
INSERT INTO supply VALUES  (206, 'table', 3);
INSERT INTO supply VALUES  (207, 'table', 4);
INSERT INTO supply VALUES  (208, 'table', 5);
INSERT INTO supply VALUES  (209, 'table', 6);
INSERT INTO supply VALUES  (210, 'table', 7);
INSERT INTO supply VALUES  (211, 'table', 8);
INSERT INTO supply VALUES  (212, 'table', 9);
INSERT INTO supply VALUES  (213, 'table', 10);
INSERT INTO supply VALUES  (214, 'table', 11);
INSERT INTO supply VALUES  (215, 'table', 12);
INSERT INTO supply VALUES  (216, 'table', 1);
INSERT INTO supply VALUES  (217, 'table', 2);
INSERT INTO supply VALUES  (218, 'table', 3);
INSERT INTO supply VALUES  (219, 'table', 4);
INSERT INTO supply VALUES  (220, 'table', 5);
INSERT INTO supply VALUES  (221, 'table', 6);
INSERT INTO supply VALUES  (222, 'table', 7);
INSERT INTO supply VALUES  (223, 'table', 8);
INSERT INTO supply VALUES  (224, 'table', 9);
INSERT INTO supply VALUES  (225, 'table', 10);
INSERT INTO supply VALUES  (226, 'table', 11);
INSERT INTO supply VALUES  (227, 'table', 12);
INSERT INTO supply VALUES  (228, 'table', 1);
INSERT INTO supply VALUES  (229, 'table', 2);
INSERT INTO supply VALUES  (230, 'table', 3);
INSERT INTO supply VALUES  (231, 'table', 4);
INSERT INTO supply VALUES  (232, 'table', 5);
INSERT INTO supply VALUES  (233, 'table', 6);
INSERT INTO supply VALUES  (234, 'table', 7);
INSERT INTO supply VALUES  (235, 'table', 8);
INSERT INTO supply VALUES  (236, 'table', 9);
INSERT INTO supply VALUES  (237, 'table', 10);
INSERT INTO supply VALUES  (238, 'table', 11);
INSERT INTO supply VALUES  (239, 'table', 12);
INSERT INTO supply VALUES  (240, 'table', 1);
INSERT INTO supply VALUES  (241, 'table', 2);
INSERT INTO supply VALUES  (242, 'table', 3);
INSERT INTO supply VALUES  (243, 'table', 4);
INSERT INTO supply VALUES  (244, 'table', 5);
INSERT INTO supply VALUES  (245, 'table', 6);
INSERT INTO supply VALUES  (246, 'table', 7);
INSERT INTO supply VALUES  (247, 'table', 8);
INSERT INTO supply VALUES  (248, 'table', 9);
INSERT INTO supply VALUES  (249, 'table', 10);
INSERT INTO supply VALUES  (250, 'table', 11);
INSERT INTO supply VALUES  (251, 'table', 12);
INSERT INTO supply VALUES  (252, 'table', 1);
INSERT INTO supply VALUES  (253, 'table', 2);
INSERT INTO supply VALUES  (254, 'table', 3);
INSERT INTO supply VALUES  (255, 'table', 4);
INSERT INTO supply VALUES  (256, 'table', 5);
INSERT INTO supply VALUES  (257, 'table', 6);
INSERT INTO supply VALUES  (258, 'table', 7);
INSERT INTO supply VALUES  (259, 'table', 8);
INSERT INTO supply VALUES  (260, 'table', 9);
INSERT INTO supply VALUES  (261, 'table', 10);
INSERT INTO supply VALUES  (262, 'table', 11);
INSERT INTO supply VALUES  (263, 'table', 12);
INSERT INTO supply VALUES  (264, 'table', 1);
INSERT INTO supply VALUES  (265, 'table', 2);
INSERT INTO supply VALUES  (266, 'table', 3);
INSERT INTO supply VALUES  (267, 'table', 4);
INSERT INTO supply VALUES  (268, 'table', 5);
INSERT INTO supply VALUES  (269, 'table', 6);
INSERT INTO supply VALUES  (270, 'table', 7);
INSERT INTO supply VALUES  (271, 'table', 8);
INSERT INTO supply VALUES  (272, 'table', 9);
INSERT INTO supply VALUES  (273, 'table', 10);
INSERT INTO supply VALUES  (274, 'table', 11);
INSERT INTO supply VALUES  (275, 'table', 12);
INSERT INTO supply VALUES  (276, 'table', 1);
INSERT INTO supply VALUES  (277, 'table', 2);
INSERT INTO supply VALUES  (278, 'table', 3);
INSERT INTO supply VALUES  (279, 'table', 4);
INSERT INTO supply VALUES  (280, 'table', 5);
INSERT INTO supply VALUES  (281, 'table', 6);
INSERT INTO supply VALUES  (282, 'table', 7);
INSERT INTO supply VALUES  (283, 'table', 8);
INSERT INTO supply VALUES  (284, 'table', 9);
INSERT INTO supply VALUES  (285, 'table', 10);
INSERT INTO supply VALUES  (286, 'table', 11);
INSERT INTO supply VALUES  (287, 'table', 12);
INSERT INTO supply VALUES  (288, 'table', 1);
INSERT INTO supply VALUES  (289, 'table', 2);
INSERT INTO supply VALUES  (290, 'table', 3);
INSERT INTO supply VALUES  (291, 'table', 4);
INSERT INTO supply VALUES  (292, 'table', 5);
INSERT INTO supply VALUES  (293, 'table', 6);
INSERT INTO supply VALUES  (294, 'table', 7);
INSERT INTO supply VALUES  (295, 'table', 8);
INSERT INTO supply VALUES  (296, 'table', 9);
INSERT INTO supply VALUES  (297, 'table', 10);
INSERT INTO supply VALUES  (298, 'table', 11);
INSERT INTO supply VALUES  (299, 'table', 12);
INSERT INTO supply VALUES  (300, 'table', 1);
INSERT INTO supply VALUES  (301, 'table', 2);
INSERT INTO supply VALUES  (302, 'table', 3);
INSERT INTO supply VALUES  (303, 'table', 4);
INSERT INTO supply VALUES  (304, 'table', 5);
INSERT INTO supply VALUES  (305, 'table', 6);
INSERT INTO supply VALUES  (306, 'table', 7);
INSERT INTO supply VALUES  (307, 'table', 8);
INSERT INTO supply VALUES  (308, 'table', 9);
INSERT INTO supply VALUES  (309, 'table', 10);
INSERT INTO supply VALUES  (310, 'table', 11);
INSERT INTO supply VALUES  (311, 'table', 12);
INSERT INTO supply VALUES  (312, 'table', 1);
INSERT INTO supply VALUES  (313, 'table', 2);
INSERT INTO supply VALUES  (314, 'table', 3);
INSERT INTO supply VALUES  (315, 'table', 4);
INSERT INTO supply VALUES  (316, 'table', 5);
INSERT INTO supply VALUES  (317, 'table', 6);
INSERT INTO supply VALUES  (318, 'table', 7);
INSERT INTO supply VALUES  (319, 'table', 8);
INSERT INTO supply VALUES  (320, 'table', 9);
INSERT INTO supply VALUES  (321, 'table', 10);
INSERT INTO supply VALUES  (322, 'table', 11);
INSERT INTO supply VALUES  (323, 'table', 12);
INSERT INTO supply VALUES  (324, 'table', 1);
INSERT INTO supply VALUES  (325, 'table', 2);
INSERT INTO supply VALUES  (326, 'table', 3);
INSERT INTO supply VALUES  (327, 'table', 4);
INSERT INTO supply VALUES  (328, 'table', 5);
INSERT INTO supply VALUES  (329, 'table', 6);
INSERT INTO supply VALUES  (330, 'table', 7);
INSERT INTO supply VALUES  (331, 'table', 8);
INSERT INTO supply VALUES  (332, 'table', 9);
INSERT INTO supply VALUES  (333, 'table', 10);
INSERT INTO supply VALUES  (334, 'table', 11);
INSERT INTO supply VALUES  (335, 'table', 12);
INSERT INTO supply VALUES  (336, 'table', 1);
INSERT INTO supply VALUES  (337, 'table', 2);
INSERT INTO supply VALUES  (338, 'table', 3);
INSERT INTO supply VALUES  (339, 'table', 4);
INSERT INTO supply VALUES  (340, 'table', 5);
INSERT INTO supply VALUES  (341, 'table', 6);
INSERT INTO supply VALUES  (342, 'table', 7);
INSERT INTO supply VALUES  (343, 'table', 8);
INSERT INTO supply VALUES  (344, 'table', 9);
INSERT INTO supply VALUES  (345, 'table', 10);
INSERT INTO supply VALUES  (346, 'table', 11);
INSERT INTO supply VALUES  (347, 'table', 12);
INSERT INTO supply VALUES  (348, 'table', 1);
INSERT INTO supply VALUES  (349, 'table', 2);
INSERT INTO supply VALUES  (350, 'table', 3);
INSERT INTO supply VALUES  (351, 'table', 4);
INSERT INTO supply VALUES  (352, 'table', 5);
INSERT INTO supply VALUES  (353, 'table', 6);
INSERT INTO supply VALUES  (354, 'table', 7);
INSERT INTO supply VALUES  (355, 'table', 8);
INSERT INTO supply VALUES  (356, 'table', 9);
INSERT INTO supply VALUES  (357, 'table', 10);
INSERT INTO supply VALUES  (358, 'table', 11);
INSERT INTO supply VALUES  (359, 'table', 12);
INSERT INTO supply VALUES  (360, 'table', 1);
INSERT INTO supply VALUES  (361, 'table', 2);
INSERT INTO supply VALUES  (362, 'table', 3);
INSERT INTO supply VALUES  (363, 'table', 4);
INSERT INTO supply VALUES  (364, 'table', 5);
INSERT INTO supply VALUES  (365, 'table', 6);
INSERT INTO supply VALUES  (366, 'table', 7);
INSERT INTO supply VALUES  (367, 'table', 8);
INSERT INTO supply VALUES  (368, 'table', 9);
INSERT INTO supply VALUES  (369, 'table', 10);
INSERT INTO supply VALUES  (370, 'table', 11);
INSERT INTO supply VALUES  (371, 'table', 12);
INSERT INTO supply VALUES  (372, 'table', 1);
INSERT INTO supply VALUES  (373, 'table', 2);
INSERT INTO supply VALUES  (374, 'table', 3);
INSERT INTO supply VALUES  (375, 'table', 4);
INSERT INTO supply VALUES  (376, 'table', 5);
INSERT INTO supply VALUES  (377, 'table', 6);
INSERT INTO supply VALUES  (378, 'table', 7);
INSERT INTO supply VALUES  (379, 'table', 8);
INSERT INTO supply VALUES  (380, 'table', 9);
INSERT INTO supply VALUES  (381, 'table', 10);
INSERT INTO supply VALUES  (382, 'table', 11);
INSERT INTO supply VALUES  (383, 'table', 12);
INSERT INTO supply VALUES  (384, 'table', 1);
INSERT INTO supply VALUES  (385, 'table', 2);
INSERT INTO supply VALUES  (386, 'table', 3);
INSERT INTO supply VALUES  (387, 'table', 4);
INSERT INTO supply VALUES  (388, 'table', 5);
INSERT INTO supply VALUES  (389, 'table', 6);
INSERT INTO supply VALUES  (390, 'table', 7);
INSERT INTO supply VALUES  (391, 'table', 8);
INSERT INTO supply VALUES  (392, 'table', 9);
INSERT INTO supply VALUES  (393, 'table', 10);
INSERT INTO supply VALUES  (394, 'table', 11);
INSERT INTO supply VALUES  (395, 'table', 12);
INSERT INTO supply VALUES  (396, 'table', 1);
INSERT INTO supply VALUES  (397, 'table', 2);
INSERT INTO supply VALUES  (398, 'table', 3);
INSERT INTO supply VALUES  (399, 'table', 4);
INSERT INTO supply VALUES  (400, 'table', 5);
INSERT INTO supply VALUES  (401, 'table', 6);
INSERT INTO supply VALUES  (402, 'table', 7);
INSERT INTO supply VALUES  (403, 'table', 8);
INSERT INTO supply VALUES  (404, 'table', 9);
INSERT INTO supply VALUES  (405, 'table', 10);
INSERT INTO supply VALUES  (406, 'table', 11);
INSERT INTO supply VALUES  (407, 'table', 12);
INSERT INTO supply VALUES  (408, 'table', 1);
INSERT INTO supply VALUES  (409, 'table', 2);
INSERT INTO supply VALUES  (410, 'table', 3);
INSERT INTO supply VALUES  (411, 'table', 4);
INSERT INTO supply VALUES  (412, 'table', 5);
INSERT INTO supply VALUES  (413, 'table', 6);
INSERT INTO supply VALUES  (414, 'table', 7);
INSERT INTO supply VALUES  (415, 'table', 8);
INSERT INTO supply VALUES  (416, 'table', 9);
INSERT INTO supply VALUES  (417, 'table', 10);
INSERT INTO supply VALUES  (418, 'table', 11);
INSERT INTO supply VALUES  (419, 'table', 12);
INSERT INTO supply VALUES  (420, 'table', 1);
INSERT INTO supply VALUES  (421, 'table', 2);
INSERT INTO supply VALUES  (422, 'table', 3);
INSERT INTO supply VALUES  (423, 'table', 4);
INSERT INTO supply VALUES  (424, 'table', 5);
INSERT INTO supply VALUES  (425, 'table', 6);
INSERT INTO supply VALUES  (426, 'table', 7);
INSERT INTO supply VALUES  (427, 'table', 8);
INSERT INTO supply VALUES  (428, 'table', 9);
INSERT INTO supply VALUES  (429, 'table', 10);
INSERT INTO supply VALUES  (430, 'table', 11);
INSERT INTO supply VALUES  (431, 'table', 12);
INSERT INTO supply VALUES  (432, 'table', 1);
INSERT INTO supply VALUES  (433, 'table', 2);
INSERT INTO supply VALUES  (434, 'table', 3);
INSERT INTO supply VALUES  (435, 'table', 4);
INSERT INTO supply VALUES  (436, 'table', 5);
INSERT INTO supply VALUES  (437, 'table', 6);
INSERT INTO supply VALUES  (438, 'table', 7);
INSERT INTO supply VALUES  (439, 'table', 8);
INSERT INTO supply VALUES  (440, 'table', 9);
INSERT INTO supply VALUES  (441, 'table', 10);
INSERT INTO supply VALUES  (442, 'table', 11);
INSERT INTO supply VALUES  (443, 'table', 12);
INSERT INTO supply VALUES  (444, 'table', 1);
INSERT INTO supply VALUES  (445, 'table', 2);
INSERT INTO supply VALUES  (446, 'table', 3);
INSERT INTO supply VALUES  (447, 'table', 4);
INSERT INTO supply VALUES  (448, 'table', 5);
INSERT INTO supply VALUES  (449, 'table', 6);
INSERT INTO supply VALUES  (450, 'table', 7);
INSERT INTO supply VALUES  (451, 'table', 8);
INSERT INTO supply VALUES  (452, 'table', 9);
INSERT INTO supply VALUES  (453, 'table', 10);
INSERT INTO supply VALUES  (454, 'table', 11);
INSERT INTO supply VALUES  (455, 'table', 12);
INSERT INTO supply VALUES  (456, 'table', 1);
INSERT INTO supply VALUES  (457, 'table', 2);
INSERT INTO supply VALUES  (458, 'table', 3);
INSERT INTO supply VALUES  (459, 'table', 4);
INSERT INTO supply VALUES  (460, 'table', 5);
INSERT INTO supply VALUES  (461, 'table', 6);
INSERT INTO supply VALUES  (462, 'table', 7);
INSERT INTO supply VALUES  (463, 'table', 8);
INSERT INTO supply VALUES  (464, 'table', 9);
INSERT INTO supply VALUES  (465, 'table', 10);
INSERT INTO supply VALUES  (466, 'table', 11);
INSERT INTO supply VALUES  (467, 'table', 12);
INSERT INTO supply VALUES  (468, 'table', 1);
INSERT INTO supply VALUES  (469, 'table', 2);
INSERT INTO supply VALUES  (470, 'table', 3);
INSERT INTO supply VALUES  (471, 'table', 4);
INSERT INTO supply VALUES  (472, 'table', 5);
INSERT INTO supply VALUES  (473, 'table', 6);
INSERT INTO supply VALUES  (474, 'table', 7);
INSERT INTO supply VALUES  (475, 'table', 8);
INSERT INTO supply VALUES  (476, 'table', 9);
INSERT INTO supply VALUES  (477, 'table', 10);
INSERT INTO supply VALUES  (478, 'table', 11);
INSERT INTO supply VALUES  (479, 'table', 12);
INSERT INTO supply VALUES  (480, 'table', 1);
INSERT INTO supply VALUES  (481, 'table', 2);
INSERT INTO supply VALUES  (482, 'table', 3);
INSERT INTO supply VALUES  (483, 'table', 4);
INSERT INTO supply VALUES  (484, 'table', 5);
INSERT INTO supply VALUES  (485, 'table', 6);
INSERT INTO supply VALUES  (486, 'table', 7);
INSERT INTO supply VALUES  (487, 'table', 8);
INSERT INTO supply VALUES  (488, 'table', 9);
INSERT INTO supply VALUES  (489, 'table', 10);
INSERT INTO supply VALUES  (490, 'table', 11);
INSERT INTO supply VALUES  (491, 'table', 12);
INSERT INTO supply VALUES  (492, 'table', 1);
INSERT INTO supply VALUES  (493, 'table', 2);
INSERT INTO supply VALUES  (494, 'table', 3);
INSERT INTO supply VALUES  (495, 'table', 4);
INSERT INTO supply VALUES  (496, 'table', 5);
INSERT INTO supply VALUES  (497, 'table', 6);
INSERT INTO supply VALUES  (498, 'table', 7);
INSERT INTO supply VALUES  (499, 'table', 8);
INSERT INTO supply VALUES  (500, 'table', 9);
INSERT INTO supply VALUES  (501, 'table', 10);
INSERT INTO supply VALUES  (502, 'table', 11);
INSERT INTO supply VALUES  (503, 'table', 12);
INSERT INTO supply VALUES  (504, 'table', 1);
INSERT INTO supply VALUES  (505, 'table', 2);
INSERT INTO supply VALUES  (506, 'table', 3);
INSERT INTO supply VALUES  (507, 'table', 4);
INSERT INTO supply VALUES  (508, 'table', 5);
INSERT INTO supply VALUES  (509, 'table', 6);
INSERT INTO supply VALUES  (510, 'table', 7);
INSERT INTO supply VALUES  (511, 'table', 8);
INSERT INTO supply VALUES  (512, 'table', 9);
INSERT INTO supply VALUES  (513, 'table', 10);
INSERT INTO supply VALUES  (514, 'table', 11);
INSERT INTO supply VALUES  (515, 'table', 12);
INSERT INTO supply VALUES  (516, 'table', 1);
INSERT INTO supply VALUES  (517, 'table', 2);
INSERT INTO supply VALUES  (518, 'table', 3);
INSERT INTO supply VALUES  (519, 'table', 4);
INSERT INTO supply VALUES  (520, 'table', 5);
INSERT INTO supply VALUES  (521, 'table', 6);
INSERT INTO supply VALUES  (522, 'table', 7);
INSERT INTO supply VALUES  (523, 'table', 8);
INSERT INTO supply VALUES  (524, 'table', 9);
INSERT INTO supply VALUES  (525, 'table', 10);
INSERT INTO supply VALUES  (526, 'table', 11);
INSERT INTO supply VALUES  (527, 'table', 12);
INSERT INTO supply VALUES  (528, 'table', 1);
INSERT INTO supply VALUES  (529, 'table', 2);
INSERT INTO supply VALUES  (530, 'table', 3);
INSERT INTO supply VALUES  (531, 'table', 4);
INSERT INTO supply VALUES  (532, 'table', 5);
INSERT INTO supply VALUES  (533, 'table', 6);
INSERT INTO supply VALUES  (534, 'table', 7);
INSERT INTO supply VALUES  (535, 'table', 8);
INSERT INTO supply VALUES  (536, 'table', 9);
INSERT INTO supply VALUES  (537, 'table', 10);
INSERT INTO supply VALUES  (538, 'table', 11);
INSERT INTO supply VALUES  (539, 'table', 12);
INSERT INTO supply VALUES  (540, 'table', 1);
INSERT INTO supply VALUES  (541, 'table', 2);
INSERT INTO supply VALUES  (542, 'table', 3);
INSERT INTO supply VALUES  (543, 'table', 4);
INSERT INTO supply VALUES  (544, 'table', 5);
INSERT INTO supply VALUES  (545, 'table', 6);
INSERT INTO supply VALUES  (546, 'table', 7);
INSERT INTO supply VALUES  (547, 'table', 8);
INSERT INTO supply VALUES  (548, 'table', 9);
INSERT INTO supply VALUES  (549, 'table', 10);
INSERT INTO supply VALUES  (550, 'table', 11);
INSERT INTO supply VALUES  (551, 'table', 12);
INSERT INTO supply VALUES  (552, 'table', 1);
INSERT INTO supply VALUES  (553, 'table', 2);
INSERT INTO supply VALUES  (554, 'table', 3);
INSERT INTO supply VALUES  (555, 'table', 4);
INSERT INTO supply VALUES  (556, 'table', 5);
INSERT INTO supply VALUES  (557, 'table', 6);
INSERT INTO supply VALUES  (558, 'table', 7);
INSERT INTO supply VALUES  (559, 'table', 8);
INSERT INTO supply VALUES  (560, 'table', 9);
INSERT INTO supply VALUES  (561, 'table', 10);
INSERT INTO supply VALUES  (562, 'table', 11);
INSERT INTO supply VALUES  (563, 'table', 12);
INSERT INTO supply VALUES  (564, 'table', 1);
INSERT INTO supply VALUES  (565, 'table', 2);
INSERT INTO supply VALUES  (566, 'table', 3);
INSERT INTO supply VALUES  (567, 'table', 4);
INSERT INTO supply VALUES  (568, 'table', 5);
INSERT INTO supply VALUES  (569, 'table', 6);
INSERT INTO supply VALUES  (570, 'table', 7);
INSERT INTO supply VALUES  (571, 'table', 8);
INSERT INTO supply VALUES  (572, 'table', 9);
INSERT INTO supply VALUES  (573, 'table', 10);
INSERT INTO supply VALUES  (574, 'table', 11);
INSERT INTO supply VALUES  (575, 'table', 12);
INSERT INTO supply VALUES  (576, 'table', 1);
INSERT INTO supply VALUES  (577, 'table', 2);
INSERT INTO supply VALUES  (578, 'table', 3);
INSERT INTO supply VALUES  (579, 'table', 4);
INSERT INTO supply VALUES  (580, 'table', 5);
INSERT INTO supply VALUES  (581, 'table', 6);
INSERT INTO supply VALUES  (582, 'table', 7);
INSERT INTO supply VALUES  (583, 'table', 8);
INSERT INTO supply VALUES  (584, 'table', 9);
INSERT INTO supply VALUES  (585, 'table', 10);
INSERT INTO supply VALUES  (586, 'table', 11);
INSERT INTO supply VALUES  (587, 'table', 12);
INSERT INTO supply VALUES  (588, 'table', 1);
INSERT INTO supply VALUES  (589, 'table', 2);
INSERT INTO supply VALUES  (590, 'table', 3);
INSERT INTO supply VALUES  (591, 'table', 4);
INSERT INTO supply VALUES  (592, 'table', 5);
INSERT INTO supply VALUES  (593, 'table', 6);
INSERT INTO supply VALUES  (594, 'table', 7);
INSERT INTO supply VALUES  (595, 'table', 8);
INSERT INTO supply VALUES  (596, 'table', 9);
INSERT INTO supply VALUES  (597, 'table', 10);
INSERT INTO supply VALUES  (598, 'table', 11);
INSERT INTO supply VALUES  (599, 'table', 12);
INSERT INTO supply VALUES  (600, 'table', 1);
INSERT INTO supply VALUES  (601, 'table', 2);
INSERT INTO supply VALUES  (602, 'table', 3);
INSERT INTO supply VALUES  (603, 'table', 4);
INSERT INTO supply VALUES  (604, 'table', 5);
INSERT INTO supply VALUES  (605, 'table', 6);
INSERT INTO supply VALUES  (606, 'table', 7);
INSERT INTO supply VALUES  (607, 'table', 8);
INSERT INTO supply VALUES  (608, 'table', 9);
INSERT INTO supply VALUES  (609, 'table', 10);
INSERT INTO supply VALUES  (610, 'table', 11);
INSERT INTO supply VALUES  (611, 'table', 12);
INSERT INTO supply VALUES  (612, 'table', 1);
INSERT INTO supply VALUES  (613, 'table', 2);
INSERT INTO supply VALUES  (614, 'table', 3);
INSERT INTO supply VALUES  (615, 'table', 4);
INSERT INTO supply VALUES  (616, 'table', 5);
INSERT INTO supply VALUES  (617, 'table', 6);
INSERT INTO supply VALUES  (618, 'table', 7);
INSERT INTO supply VALUES  (619, 'table', 8);
INSERT INTO supply VALUES  (620, 'table', 9);
INSERT INTO supply VALUES  (621, 'table', 10);
INSERT INTO supply VALUES  (622, 'table', 11);
INSERT INTO supply VALUES  (623, 'table', 12);
INSERT INTO supply VALUES  (624, 'table', 1);
INSERT INTO supply VALUES  (625, 'table', 2);
INSERT INTO supply VALUES  (626, 'table', 3);
INSERT INTO supply VALUES  (627, 'table', 4);
INSERT INTO supply VALUES  (628, 'table', 5);
INSERT INTO supply VALUES  (629, 'table', 6);
INSERT INTO supply VALUES  (630, 'table', 7);
INSERT INTO supply VALUES  (631, 'table', 8);
INSERT INTO supply VALUES  (632, 'table', 9);
INSERT INTO supply VALUES  (633, 'table', 10);
INSERT INTO supply VALUES  (634, 'table', 11);
INSERT INTO supply VALUES  (635, 'table', 12);
INSERT INTO supply VALUES  (636, 'table', 1);
INSERT INTO supply VALUES  (637, 'table', 2);
INSERT INTO supply VALUES  (638, 'table', 3);
INSERT INTO supply VALUES  (639, 'table', 4);
INSERT INTO supply VALUES  (640, 'table', 5);
INSERT INTO supply VALUES  (641, 'table', 6);
INSERT INTO supply VALUES  (642, 'table', 7);
INSERT INTO supply VALUES  (643, 'table', 8);
INSERT INTO supply VALUES  (644, 'table', 9);
INSERT INTO supply VALUES  (645, 'table', 10);
INSERT INTO supply VALUES  (646, 'table', 11);
INSERT INTO supply VALUES  (647, 'table', 12);
INSERT INTO supply VALUES  (648, 'table', 1);
INSERT INTO supply VALUES  (649, 'table', 2);
INSERT INTO supply VALUES  (650, 'table', 3);
INSERT INTO supply VALUES  (651, 'table', 4);
INSERT INTO supply VALUES  (652, 'table', 5);
INSERT INTO supply VALUES  (653, 'table', 6);
INSERT INTO supply VALUES  (654, 'table', 7);
INSERT INTO supply VALUES  (655, 'table', 8);
INSERT INTO supply VALUES  (656, 'table', 9);
INSERT INTO supply VALUES  (657, 'table', 10);
INSERT INTO supply VALUES  (658, 'table', 11);
INSERT INTO supply VALUES  (659, 'table', 12);
INSERT INTO supply VALUES  (660, 'table', 1);
INSERT INTO supply VALUES  (661, 'table', 2);
INSERT INTO supply VALUES  (662, 'table', 3);
INSERT INTO supply VALUES  (663, 'table', 4);
INSERT INTO supply VALUES  (664, 'table', 5);
INSERT INTO supply VALUES  (665, 'table', 6);
INSERT INTO supply VALUES  (666, 'table', 7);
INSERT INTO supply VALUES  (667, 'table', 8);
INSERT INTO supply VALUES  (668, 'table', 9);
INSERT INTO supply VALUES  (669, 'table', 10);
INSERT INTO supply VALUES  (670, 'table', 11);
INSERT INTO supply VALUES  (671, 'table', 12);
INSERT INTO supply VALUES  (672, 'table', 1);
INSERT INTO supply VALUES  (673, 'table', 2);
INSERT INTO supply VALUES  (674, 'table', 3);
INSERT INTO supply VALUES  (675, 'table', 4);
INSERT INTO supply VALUES  (676, 'table', 5);
INSERT INTO supply VALUES  (677, 'table', 6);
INSERT INTO supply VALUES  (678, 'table', 7);
INSERT INTO supply VALUES  (679, 'table', 8);
INSERT INTO supply VALUES  (680, 'table', 9);
INSERT INTO supply VALUES  (681, 'table', 10);
INSERT INTO supply VALUES  (682, 'table', 11);
INSERT INTO supply VALUES  (683, 'table', 12);
INSERT INTO supply VALUES  (684, 'table', 1);
INSERT INTO supply VALUES  (685, 'table', 2);
INSERT INTO supply VALUES  (686, 'table', 3);
INSERT INTO supply VALUES  (687, 'table', 4);
INSERT INTO supply VALUES  (688, 'table', 5);
INSERT INTO supply VALUES  (689, 'table', 6);
INSERT INTO supply VALUES  (690, 'table', 7);
INSERT INTO supply VALUES  (691, 'table', 8);
INSERT INTO supply VALUES  (692, 'table', 9);
INSERT INTO supply VALUES  (693, 'table', 10);
INSERT INTO supply VALUES  (694, 'table', 11);
INSERT INTO supply VALUES  (695, 'table', 12);
INSERT INTO supply VALUES  (696, 'table', 1);
INSERT INTO supply VALUES  (697, 'table', 2);
INSERT INTO supply VALUES  (698, 'table', 3);
INSERT INTO supply VALUES  (699, 'table', 4);
INSERT INTO supply VALUES  (700, 'table', 5);
INSERT INTO supply VALUES  (701, 'table', 6);
INSERT INTO supply VALUES  (702, 'table', 7);
INSERT INTO supply VALUES  (703, 'table', 8);
INSERT INTO supply VALUES  (704, 'table', 9);
INSERT INTO supply VALUES  (705, 'table', 10);
INSERT INTO supply VALUES  (706, 'table', 11);
INSERT INTO supply VALUES  (707, 'table', 12);
INSERT INTO supply VALUES  (708, 'table', 1);
INSERT INTO supply VALUES  (709, 'table', 2);
INSERT INTO supply VALUES  (710, 'table', 3);
INSERT INTO supply VALUES  (711, 'table', 4);
INSERT INTO supply VALUES  (712, 'table', 5);
INSERT INTO supply VALUES  (713, 'table', 6);
INSERT INTO supply VALUES  (714, 'table', 7);
INSERT INTO supply VALUES  (715, 'table', 8);
INSERT INTO supply VALUES  (716, 'table', 9);
INSERT INTO supply VALUES  (717, 'table', 10);
INSERT INTO supply VALUES  (718, 'table', 11);
INSERT INTO supply VALUES  (719, 'table', 12);
INSERT INTO supply VALUES  (720, 'table', 1);
INSERT INTO supply VALUES  (721, 'table', 2);
INSERT INTO supply VALUES  (722, 'table', 3);
INSERT INTO supply VALUES  (723, 'table', 4);
INSERT INTO supply VALUES  (724, 'table', 5);
INSERT INTO supply VALUES  (725, 'table', 6);
INSERT INTO supply VALUES  (726, 'table', 7);
INSERT INTO supply VALUES  (727, 'table', 8);
INSERT INTO supply VALUES  (728, 'table', 9);
INSERT INTO supply VALUES  (729, 'table', 10);
INSERT INTO supply VALUES  (730, 'table', 11);
INSERT INTO supply VALUES  (731, 'table', 12);
INSERT INTO supply VALUES  (732, 'table', 1);
INSERT INTO supply VALUES  (733, 'table', 2);
INSERT INTO supply VALUES  (734, 'table', 3);
INSERT INTO supply VALUES  (735, 'table', 4);
INSERT INTO supply VALUES  (736, 'table', 5);
INSERT INTO supply VALUES  (737, 'table', 6);
INSERT INTO supply VALUES  (738, 'table', 7);
INSERT INTO supply VALUES  (739, 'table', 8);
INSERT INTO supply VALUES  (740, 'table', 9);
INSERT INTO supply VALUES  (741, 'table', 10);
INSERT INTO supply VALUES  (742, 'table', 11);
INSERT INTO supply VALUES  (743, 'table', 12);
INSERT INTO supply VALUES  (744, 'table', 1);
INSERT INTO supply VALUES  (745, 'table', 2);
INSERT INTO supply VALUES  (746, 'table', 3);


INSERT INTO is_for VALUES (11, 2);
INSERT INTO is_for VALUES (4, 3);
INSERT INTO is_for VALUES (6, 4);
INSERT INTO is_for VALUES (9, 5);
INSERT INTO is_for VALUES (13, 6);
INSERT INTO is_for VALUES (1, 7);
INSERT INTO is_for VALUES (15, 8);
INSERT INTO is_for VALUES (7, 9);
INSERT INTO is_for VALUES (18, 10);
INSERT INTO is_for VALUES (16, 1);
INSERT INTO is_for VALUES (8, 2);
INSERT INTO is_for VALUES (5, 3);
INSERT INTO is_for VALUES (3, 4);
INSERT INTO is_for VALUES (17, 5);
INSERT INTO is_for VALUES (14, 6);
INSERT INTO is_for VALUES (2, 7);
INSERT INTO is_for VALUES (12, 8);
INSERT INTO is_for VALUES (10, 9);
INSERT INTO is_for VALUES (11, 10);
INSERT INTO is_for VALUES (4, 1);
INSERT INTO is_for VALUES (6, 2);
INSERT INTO is_for VALUES (9, 3);
INSERT INTO is_for VALUES (13, 4);
INSERT INTO is_for VALUES (1, 5);
INSERT INTO is_for VALUES (15, 6);
INSERT INTO is_for VALUES (7, 7);


INSERT INTO required_request VALUES (109, 5);
INSERT INTO required_request VALUES (93, 6);
INSERT INTO required_request VALUES (165, 11);
INSERT INTO required_request VALUES (166, 9);
INSERT INTO required_request VALUES (98, 7);
INSERT INTO required_request VALUES (110, 2);
INSERT INTO required_request VALUES (32, 15);
INSERT INTO required_request VALUES (169, 14);
INSERT INTO required_request VALUES (26, 18);
INSERT INTO required_request VALUES (157, 10);
INSERT INTO required_request VALUES (94, 4);


INSERT INTO approved_request VALUES (8, 15);
INSERT INTO approved_request VALUES (170, 10);
INSERT INTO approved_request VALUES (124, 3);
INSERT INTO approved_request VALUES (158, 4);
INSERT INTO approved_request VALUES (102, 5);
INSERT INTO approved_request VALUES (182, 11);
INSERT INTO approved_request VALUES (76, 1);
INSERT INTO approved_request VALUES (5, 7);
INSERT INTO approved_request VALUES (41, 12);
INSERT INTO approved_request VALUES (26, 16);
INSERT INTO approved_request VALUES (172, 14);
INSERT INTO approved_request VALUES (69, 9);
INSERT INTO approved_request VALUES (133, 8);
INSERT INTO approved_request VALUES (160, 2);
INSERT INTO approved_request VALUES (178, 13);
INSERT INTO approved_request VALUES (151, 6);


INSERT INTO member_of_chat VALUES (6, 19);
INSERT INTO member_of_chat VALUES (2, 1);
INSERT INTO member_of_chat VALUES (12, 27);
INSERT INTO member_of_chat VALUES (16, 22);
INSERT INTO member_of_chat VALUES (18, 9);
INSERT INTO member_of_chat VALUES (13, 2);
INSERT INTO member_of_chat VALUES (14, 16);
INSERT INTO member_of_chat VALUES (15, 17);
INSERT INTO member_of_chat VALUES (10, 11);
INSERT INTO member_of_chat VALUES (5, 12);
INSERT INTO member_of_chat VALUES (8, 23);
INSERT INTO member_of_chat VALUES (7, 10);
INSERT INTO member_of_chat VALUES (1, 21);
INSERT INTO member_of_chat VALUES (3, 24);
INSERT INTO member_of_chat VALUES (9, 4);
INSERT INTO member_of_chat VALUES (11, 7);
INSERT INTO member_of_chat VALUES (4, 25);
INSERT INTO member_of_chat VALUES (17, 6);
INSERT INTO member_of_chat VALUES (6, 26);
INSERT INTO member_of_chat VALUES (2, 20);
INSERT INTO member_of_chat VALUES (12, 18);
INSERT INTO member_of_chat VALUES (16, 8);
INSERT INTO member_of_chat VALUES (18, 3);
INSERT INTO member_of_chat VALUES (13, 15);
INSERT INTO member_of_chat VALUES (14, 5);
INSERT INTO member_of_chat VALUES (15, 13);
INSERT INTO member_of_chat VALUES (10, 14);


INSERT INTO web_page VALUES (1, 17);
INSERT INTO web_page VALUES (2, 4);
INSERT INTO web_page VALUES (3, 1);
INSERT INTO web_page VALUES (4, 12);
INSERT INTO web_page VALUES (5, 5);
INSERT INTO web_page VALUES (6, 11);
INSERT INTO web_page VALUES (7, 15);
INSERT INTO web_page VALUES (8, 3);
INSERT INTO web_page VALUES (9, 10);
INSERT INTO web_page VALUES (10, 18);
INSERT INTO web_page VALUES (11, 16);
INSERT INTO web_page VALUES (12, 9);
INSERT INTO web_page VALUES (13, 7);
INSERT INTO web_page VALUES (14, 13);
INSERT INTO web_page VALUES (15, 2);
INSERT INTO web_page VALUES (16, 8);
INSERT INTO web_page VALUES (17, 14);
INSERT INTO web_page VALUES (18, 6);
INSERT INTO web_page VALUES (19, 17);
INSERT INTO web_page VALUES (20, 4);
INSERT INTO web_page VALUES (21, 1);


INSERT INTO content VALUES (1, 9, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (2, 5, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (3, 6, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (4, 13, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (5, 8, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (6, 19, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (7, 3, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (8, 1, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (9, 15, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (10, 12, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (11, 20, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (12, 2, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (13, 10, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (14, 4, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (15, 16, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (16, 18, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (17, 21, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (18, 7, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (19, 11, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (20, 14, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (21, 17, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (22, 9, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (23, 5, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (24, 6, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (25, 13, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (26, 8, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (27, 19, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (28, 3, 'This is first draft of hospital`s website');
INSERT INTO content VALUES (29, 1, 'This is first draft of hospital`s website');


